### ISSUE TITLE
TFS 1.2 (Ninja) MyACC 0.7.9 Ban page issue 

### ISSUE THREAD

**Issue by Bright1G** [slawkens/myaac#100]
As far as i understand ban pages doesnt work with tfs 1.2 (Ninja version)? Even with newest myacc version because i tried using latest ban page. 
Bans.php
https://pastebin.com/M8j12QeT

**Comment by slawkens** [comment]
No, it won't work because TFS 1.2 bans table doesn't contain any useful information. It contains only account_id, which we don't want to expose.
