### ISSUE TITLE
cache vulnerability 

### ISSUE THREAD

**Issue by MoisesFV** [slawkens/myaac#101]
When htacess settings are not enabled, the cache is exposed. I had a problem with that. I'm a novice user, but many novice users use myaac. maybe the cache should not store the mysql password and other sensitive data.

**Comment by slawkens** [comment]
The cache is exposed, that's right. But it's almost impossible to guess the name of the cached file with mysql password - am I wrong?

The one solution would be to put system/cache outside public/ folder, which will be part of MyAAC as of 2.0

**Comment by MoisesFV** [comment]
Yes really. The problem is if you don't have -indexes in htacess. the user freely navigates through the folders

**Comment by slawkens** [comment]
Oh, thats the problem then. Did you completely disabled .htaccess files reading? Or was that the case by default in your web-server?

**Comment by slawkens** [comment]
What about adding index.html in the cache folder? It should hide that auto-indexes option? Can you test that?

**Comment by MoisesFV** [comment]
I use ubuntu 16.04. By default apache for this release has the AllowOverride None option. If we do not switch to AllowOverride All the directory listing is exposed
