### ISSUE TITLE
Hidden character bugs out character page

### ISSUE THREAD

**Issue by gerotib** [slawkens/myaac#106]
While character is hidden, at least on "tibiacom" template, right pannels goes inwards and some other things on character page bugs out. 
![kat](https://user-images.githubusercontent.com/29408915/73849491-529bf400-482a-11ea-9539-62fdc0355b2d.jpg)
Credit to [Gabe120](https://otland.net/members/gabe120.77838/) for screenshot. (on my aac it looks the same and im using current github version)

**Comment by slawkens** [comment]
Hello,

thanks for your report. I will look into it when I'm back from work.

**Comment by slawkens** [comment]
I can't reproduce this.

What browser and what MyAAC version are you using?

Also, can you share your config.php, especially this part?
```
	// characters page
	'characters' => array( // what things to display on character view page (true/false in each option)
		'level' => true,
		'experience' => false,
		'magic_level' => false,
		'balance' => false,
		'marriage_info' => true, // only 0.3
		'outfit' => true,
		'creation_date' => true,
		'quests' => false,
		'skills' => false,
		'equipment' => false,
		'frags' => false,
		'deleted' => true, // should deleted characters from same account be still listed on the list of characters? When enabled it will show that character is "[DELETED]"
	),
	'quests' => array(), // quests list (displayed in character view), name => storage
	'signature_enabled' => false,
```

**Comment by slawkens** [comment]
Maybe this helps?

https://github.com/slawkens/myaac/commit/071289bc483d4bae2c6a695f8e103c0e9241fe88

**Comment by gerotib** [comment]
Yeah, thats what caused it, good job :D
