### ISSUE TITLE
 Error displaying loot items from monsters

### ISSUE THREAD

**Issue by MoisesFV** [slawkens/myaac#107]
![error](https://user-images.githubusercontent.com/27247705/74794601-6c195300-52a2-11ea-99e6-6fc2df4951b3.png)
When trying to load a monster an error occurs when loading items

**Comment by slawkens** [comment]
Hello,

Thanks for your report.

I just fixed it in this commit: https://github.com/slawkens/myaac/commit/8c680608ffcbdc2ac920a60c5bc9d36d091ebcda
