### ISSUE TITLE
Top Fragger issue

### ISSUE THREAD

**Issue by Aerwix** [slawkens/myaac#108]
#11 # Server configuration
- Operating System: Debian 10
- Web Server (+ version): nginx 
- PHP Version: 7.0 debug or something like that
- Server name and version (for example: TFS 0.3): otx4 based on 1.2 TFS
- MyAAC Version: 8

### Client configuration (Your Computer)

- Browser: Google Chrome
- Operating System: Windows 10

### Description:
I tried to add a new page called "Top Fraggers", found the code and tested with 7.12 and 7.11 and was working everything fine.
Working on 7.11, 7.12 https://media.discordapp.net/attachments/454438436619943936/680234065001316373/unknown.png

And then send it to my VPS which is 8.0 (dev mode)
https://media.discordapp.net/attachments/454438436619943936/680234145741275156/unknown.png

### Steps To Reproduce:
Create a new page with the /admin helper
Insert PHP code:
https://gist.github.com/Aerwix/e821c19f1dd0a1d1b31036fd0b45a705

**Comment by slawkens** [comment]
Hello,

The solution would be to change $SQL to $db.

But I will look into it when I'm back from work, so it will work with $SQL too.

Thanks for the detailed report.

**Comment by Aerwix** [comment]
Hello Slawkens,

Actually swapped from $SQL to $db but...

Now:
- The page can be loaded but dont show anything.
https://media.discordapp.net/attachments/454438436619943936/681188169315909636/unknown.png

Thanks for your help. :)

**Comment by slawkens** [comment]
Hello,

I just fixed it in this commit - https://github.com/slawkens/myaac/commit/fcfad7cef9160b86d4dcc5a880d42f4b5bb2e7e5

**Comment by slawkens** [comment]
Hello @Aerwix,

Did that commit fix your issue?

**Comment by Aerwix** [comment]
Hello @slawkens

Actually yes, now is working fine.

Proof: https://demera.online/?topfraggers
