### ISSUE TITLE
not install curl? for sms-shop? not work

### ISSUE THREAD

**Issue by cocaocla** [slawkens/myaac#110]
I am trying to upload the SMS-SHOP plugin but it keeps crashing that I don't have CURL installed. and I have installed on my vps
![image](https://user-images.githubusercontent.com/57010926/76473030-9371c480-63f7-11ea-986f-a15079e86ec3.png)

im have installed
![image](https://user-images.githubusercontent.com/57010926/76473054-a7b5c180-63f7-11ea-9c6d-bebac4efe361.png)

**Comment by slawkens** [comment]
it's not just curl, but php-curl. 

try
apt install php-curl 

then
sudo service apache2 restart

**Comment by cocaocla** [comment]
ahh thanks me bad :d im use apt-get install curl ehh sorry

**Comment by cocaocla** [comment]
such a stepping stone. don't you think that when you register with the aldora template you don't see the inscriptions account name etc etc?
could you not tell me how to brighten these inscriptions?

**Comment by slawkens** [comment]
> such a stepping stone. don't you think that when you register with the aldora template you don't see the inscriptions account name etc etc?
> could you not tell me how to brighten these inscriptions?

I fixed it here:
https://github.com/slawkens/myaac-plugins/commit/2ec27388bdd59c8906ceca508aa00d863d61a67e

Closing, as problem has been solved.
