### ISSUE TITLE
myacc crashing

### ISSUE THREAD

**Issue by cocaocla** [slawkens/myaac#112]
myacc hangs on news, tickers, changelog editions, the database is changed and what was previously on the page. restart mysql-server, nginx gives nothing,

![image](https://user-images.githubusercontent.com/57010926/77590976-43165e80-6eef-11ea-977c-a9bfc2f148d9.png)

it is weak and slow, the player has created a 400 level character and is not in highsorcer
can you help me?

**Comment by cocaocla** [comment]
I will add that the new archive shows up, and the main page does not: / and the same is with post deletion, the new archive is removed and the last news is not, I add that I cleaned cooke, I looked at other computers the same,

**Comment by slawkens** [comment]
What MyAAC Version?

If its 0.8.0, then you can add something like that, to check if it's mysql performing slow:
https://github.com/slawkens/myaac/commit/e7fa5eb38ae39936e5c08ab3fa486d64579150d2

**Comment by cocaocla** [comment]
version the latest version that could be downloaded from you from github, would you tell me how to see if mysql is slow? but when I reinstalled 3x myacc site it worked fine at first, for 3-4 hours and then very slowly

**Comment by slawkens** [comment]
What do you have in config.local.php, under $config['env']?

Copy the code I posted above (you can replace the whole file - system/libs/pot/OTS_Base_DB.php), then set database_log to true in config.php, and then look into system/logs/database.log to see how much time it took to execute a query.

**Comment by cocaocla** [comment]
I've got $ config ['env'] = 'prod'; // dev or prod
I have replaced the entire contents of the files and I get an error and there is no log

**Comment by cocaocla** [comment]
something like that appeared

[Thu, 26 Mar 2020 02:25:44 +0100] /
SELECT `name`, `value` FROM `myaac_config` WHERE `name` LIKE "%status%"
SELECT `value` FROM `myaac_config` WHERE `name` = 'database_version'
SELECT `value` FROM `myaac_config` WHERE `name` = 'site_closed'
SELECT `id`, `title`, `body`, `php`, `hidden` FROM `myaac_pages` WHERE `name` LIKE 'news' AND `hidden` != 1 AND `access` <= '1'
SELECT `id`, `name`, `level`, `experience`, `looktype`, `lookaddons`, `lookhead`, `lookbody`, `looklegs`, `lookfeet`, `online` FROM `players` WHERE `group_id` < 3 AND `id` NOT IN (1, 3, 4, 5, 6, 7) AND `deleted` = 0 AND `account_id` != 1 ORDER BY `experience` DESC LIMIT 5
SELECT `thumb` FROM `myaac_gallery` WHERE `id` = '1'
SELECT `id`, `question` FROM `z_polls` WHERE end > 1585185944 ORDER BY `end` LIMIT 1

**Comment by slawkens** [comment]
If you would copy the code I posted, then you would also see the time it took for each query.

I don't understand the problem you are having. The site is slow? What does it show in page footer in Load Time?

**Comment by cocaocla** [comment]
Load time: 0.0461 seconds.

the point is that, I add a post via, admin panel, it does not appear immediately only with a delay and a large one, same with items in sms hop or tickers, in highsorcers neither people appear

**Comment by cocaocla** [comment]
I downloaded myacc 4 times and it's still the same

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/77601058-fc822d80-6f09-11ea-8357-5414753b542e.png)
![image](https://user-images.githubusercontent.com/57010926/77601077-07d55900-6f0a-11ea-8fe3-013ea98ad337.png)

you see, I added the test and it didn't appear, in the database I have it on the page,

**Comment by cocaocla** [comment]
look 
![image](https://user-images.githubusercontent.com/57010926/77601151-35ba9d80-6f0a-11ea-81e7-85dd107930d5.png)

**Comment by slawkens** [comment]
OK I fixed that news bug here - https://github.com/slawkens/myaac/commit/87e54ac14f98c6f0e56f71422f55642d521efe35

**Comment by cocaocla** [comment]
will the new ticker work well now?

**Comment by slawkens** [comment]
Yes you will just need to remove/edit/add some news/article/ticker to make it work.

**Comment by cocaocla** [comment]
thank you mate, it works and it's good, you are great and you have a lot of experience compared to me, thank you again that you did not fail me, keep up the good work, best regards
