### ISSUE TITLE
Guild creation problem

### ISSUE THREAD

**Issue by cocaocla** [slawkens/myaac#113]
error appears when creating a guild
![image](https://user-images.githubusercontent.com/57010926/77670510-97b8e880-6f86-11ea-9e39-ac9e3a849b49.png)

can you help me somehow?

**Comment by slawkens** [comment]
more info I need: server name and version

**Comment by cocaocla** [comment]
Theforgotten serwer, tfs 0.4.0
8.6

**Comment by cocaocla** [comment]
if you need any more, tell me and I'll give you everything you need

**Comment by cocaocla** [comment]
could you also help me add a power guild bridge because it won't work, the latest news page doesn't work after adding, and only shows the most power guild

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/77672842-ace34680-6f89-11ea-9247-7bc75984162e.png)
after adding power-full bridge I have this error

**Comment by slawkens** [comment]
> ![image](https://user-images.githubusercontent.com/57010926/77672842-ace34680-6f89-11ea-9247-7bc75984162e.png)
> after adding power-full bridge I have this error

Try adding this in plugins/powerful-guilds/powerful-guilds.php
```
$db->query("SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));");
```
Just before:
```
function mostPowerfulGuildsDatabase()
```

**Comment by slawkens** [comment]
> error appears when creating a guild
> ![image](https://user-images.githubusercontent.com/57010926/77670510-97b8e880-6f86-11ea-9e39-ac9e3a849b49.png)
> 
> can you help me somehow?

Try execute this in phpmyadmin on your database:
```sql
ALTER TABLE guilds DROP checkdata;
```

**Comment by cocaocla** [comment]
I have another mistake
when creating a game account, myacc does not encode in sha1 just another type. and config.lua is sha1. the page reads the password and the server no longer. after reinstallation, myacc works for about 1 hour and again does not work and codes anyhow that you do not know what the password is. after changing in phpmyadmin the password encoded in sha1 goes to log in to the server. and by changing the password through the site it is still impossible to log in

**Comment by cocaocla** [comment]
powerfull-guild OK!

Create guild is next error? Please Help.
![image](https://user-images.githubusercontent.com/57010926/77814260-a0590e00-70af-11ea-8b3c-8bb6762cd705.png)

**Comment by slawkens** [comment]
Execute this on your database in phpmyadmin:
```sql
ALTER TABLE `guilds` MODIFY `motd` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `guilds` ADD `checkdata` INT NOT NULL DEFAULT 0 AFTER `creationdata`;
```

**Comment by cocaocla** [comment]
now there is a problem that after creating the guild does not assign a member to the guild after creation immediately deletes it.

**Comment by cocaocla** [comment]
would you be able to help me do more sms hop sections? because I wanted to add mage, knight, paladin, and that they were itemki, that they would be separate departments for them, because I can't change

**Comment by cocaocla** [comment]
Wiesz może łatwiej będzie się ze mną dogadać po polsku ponieważ mój angielski kulawy, problemy up zostały rozwiązane dobrze. Tylko teraz przy zmianie opisu guildi wywala błąd taki:
![image](https://user-images.githubusercontent.com/57010926/77866445-66187980-7233-11ea-86ae-497fe7429049.png)
Wiem że jestem upierdliwy ale wybacz. I czy nie pomógł byś mi zrobić z 5-6 działów w sms shopie?. np Mage, Knight, Paladin. chodzi o to żeby normalnie wysyłało itemki. ponieważ jak zmieniłem w bazie danych np others na items, to nie pokazywało się to na stronie.

**Comment by slawkens** [comment]
> Wiesz może łatwiej będzie się ze mną dogadać po polsku ponieważ mój angielski kulawy, problemy up zostały rozwiązane dobrze. Tylko teraz przy zmianie opisu guildi wywala błąd taki:
> ![image](https://user-images.githubusercontent.com/57010926/77866445-66187980-7233-11ea-86ae-497fe7429049.png)
> Wiem że jestem upierdliwy ale wybacz. I czy nie pomógł byś mi zrobić z 5-6 działów w sms shopie?. np Mage, Knight, Paladin. chodzi o to żeby normalnie wysyłało itemki. ponieważ jak zmieniłem w bazie danych np others na items, to nie pokazywało się to na stronie.

You need to install this packet: https://stackoverflow.com/a/51094250/1055314

To make more categories in shop, you need to edit z_shop_categories in your database.

**Comment by cocaocla** [comment]
tak próbowałem edytować to w phpmyadmin, ale po dodaniu nowego to nie wyskakuje mi żeby wpisać id czy też ile mo dać danego przedmiotu.

**Comment by cocaocla** [comment]
Ponieważ nie rozumiem twojego themplates, i systemu myaac czy byś mógł mi powiedzieć gdzie mogę pozmieniać te ikonki? 
![image](https://user-images.githubusercontent.com/57010926/77971960-61fe6180-72f0-11ea-93ed-c619221cd8b5.png)
