### ISSUE TITLE
Bug admin panel

### ISSUE THREAD

**Issue by malborobeck** [slawkens/myaac#114]
### Server configuration
- Operating System: 
- Web Server (+ version): 
- PHP Version: 7.2
- Server name and version (for example: TFS 0.3): otx2
- MyAAC Version:  the most recent

### Client configuration (Your Computer)

- Browser: chrome
- Operating System: windows 10

### Description:
in the admin panel, it is not possible to find an account that has only numbers

### Steps To Reproduce:

**Comment by cocaocla** [comment]
download an earlier version of Aaac. then it should work

**Comment by cocaocla** [comment]
or wait I will throw you the correct version of admin panel

**Comment by cocaocla** [comment]
Simply replace the files in var / www / html.
[https://megawrzuta.pl/download/005c485e1f20555c25e485cde072b152.html](url)

and then it should work properly

**Comment by malborobeck** [comment]
replaces the files and it is still not possible to find an account in the editor / account menu that contains only numbers

**Comment by cocaocla** [comment]
@slawkens  can you help Because it works fine with my files.

**Comment by ivenspontes** [comment]
if you look for the number, it will look for the account ID

**Comment by Leesneaks** [comment]
Sorry, I didn't notice this comment, I will push an update for this soon.
![image](https://user-images.githubusercontent.com/42119604/78255589-5e84f900-74ef-11ea-956e-38ef58780362.png)
