### ISSUE TITLE
website crash. 

### ISSUE THREAD

**Issue by cocaocla** [slawkens/myaac#115]
hello I have such a problem, the server has been shut down and I'm still online
![image](https://user-images.githubusercontent.com/57010926/78444159-201b4580-7679-11ea-8bb8-923e92c47958.png)
![image](https://user-images.githubusercontent.com/57010926/78444273-2c070780-7679-11ea-8360-27a4348e3fa7.png)

the visit counter hung up

![image](https://user-images.githubusercontent.com/57010926/78444450-3923f680-7679-11ea-9732-7803a1bed0aa.png)
and does anyone know how to change it? that it would be mine, for example?
![image](https://user-images.githubusercontent.com/57010926/78444750-4e992080-7679-11ea-9eae-49df76968b65.png)

System: ubuntu 16.04
nginx: nginx version: nginx/1.10.3 (Ubuntu)
PHP Version 7.0.33-0ubuntu0.16.04.12
Vps 12 gb ram, 2 core,

**Comment by Leesneaks** [comment]
The online count just pulls from the database, whether the user has been set online or not via ingame.
It appears you haven't shutdown the server properly or have changed the code that removes a player from the database, 
I am going to assume you are using TFS from the git
https://github.com/otland/forgottenserver/blob/master/data/globalevents/scripts/startup.lua#L3

This file clears out the players online on startup.
I assume you have just closed the server without shutting it down and it hasn't logged your admin off (logout removes the logged in field from db).

The online list doesn't have caching, so should be pretty live feed as long as the server is updating the fields correctly.
see here:
https://github.com/slawkens/myaac/blob/master/system/pages/online.php#L54

The visitor count is done inside of this file and checks IP addresses from who is visiting the website.
https://github.com/slawkens/myaac/blob/master/system/libs/visitors.php
Currently it is saying your page has been viewed 2 times and there is currently one visitor, if you have just setup the database, this would be correct.

As for your last image, i assume you mean you want to change the facebook network.
https://github.com/slawkens/myaac/blob/master/templates/tibiacom/config.ini#L11

What exactly has "hung up" on it? how has it "crashed"?

**Comment by cocaocla** [comment]
the visitor counter was working properly until 9201, something like this, and it hung.

now I have another problem because when I go to the latest news, I don't have the right bar and it was still there
![image](https://user-images.githubusercontent.com/57010926/78460420-13224480-76c1-11ea-94a8-f9f0fd192ec4.png)
appears after some page refresh

**Comment by Leesneaks** [comment]
Do you have a link to this website that is live?
If you have installed it correctly it works out of the box. There have been no new changes which would have broken these bars. (I am using it on a live server and 2 test servers).
What changes have you made.

As for the visitor counter, it is saved in the database, have you changed database? In your previous issue, you mentioned you changed the database.

There are websites out there that have a lot more views.
![image](https://user-images.githubusercontent.com/42119604/78460511-48c32f80-76b9-11ea-8457-4d37ab1bedd8.png)

**Comment by cocaocla** [comment]
yes i can give you. I didn't change anything
http://merestia.online

**Comment by cocaocla** [comment]
after the change of facebook normally the right side appears again

**Comment by Leesneaks** [comment]
What plugins are you running?
Are you running the most recent commit? template and all?

**Comment by cocaocla** [comment]
yes 
gesior shop, countdown,

**Comment by tobi132** [comment]
What do you have in config.local.php, under $config['env']? Prod or dev?

**Comment by Leesneaks** [comment]
Its only seems to be your main page that is doing it.
What boxes do you have loaded?
Gallery and poll both only work on the news page.

I am currently on discord if this is easier for you.
Lee#7225

**Comment by cocaocla** [comment]
and I have another problem because if a player creates guilds, he doesn't add him as a leader
![image](https://user-images.githubusercontent.com/57010926/78462234-78316680-76d0-11ea-9d24-9a67c1b66033.png)
all is well now only this guild, what is created guilds does not add a player like a leader, what created guilds

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/78462265-a3b45100-76d0-11ea-9bf6-dbb66f59e655.png)
I can't remove deflation

**Comment by Leesneaks** [comment]
Your web logs must be showing an error of some kind of errors, please check them and show the errors.
Without these it maybe near impossible to predict.
I recommend you uninstall all the plugins first.

I've tested them on my 2 servers and they are working with a refresh install and they are working, too many issues, i don't think it has been setup correctly or something has been modified.

Start-cooldown is on version 1.1 on the git which comes with the uninstall option.

**Comment by cocaocla** [comment]
could you tell me where to find the logs?

**Comment by cocaocla** [comment]
i found the logs nothing there is showing no error

**Comment by Leesneaks** [comment]
That would depend on your setup, linux, windows. Apache, Nginx, etc.
Atm, it is seeming like a bad setup or something modified.

The server logs would show an error when the page fails to display like it does.
Something is failing. Please remove all plugins.

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/78462808-f2b0b500-76d5-11ea-962b-abc0cf606532.png)
similarly why can't I choose here? I don't know how to set it up and can't use the editor
I don't know, now everything works correctly, it has fixed itself

**Comment by Leesneaks** [comment]
https://github.com/slawkens/myaac/blob/9b3dbdc54ff23792c2b66bbce4ddc12c1afbd085/system/init.php#L183

tfs 1.3 comes with a towns entry in the database.
You either haven't got this or haven't setup your Towns array in config.
If you don't use the table in the database just comment out line 183 to 203 and just use the bottom part.
I would consider all these issues resolved now.

**Comment by tobi132** [comment]
download here the latest start-countdown with uninstall option: https://drive.google.com/file/d/1q723nra_i3T_L0N4ta7QrQr9ZKmmYsgF/view?usp=sharing

install it, then uninstall :P

**Comment by cocaocla** [comment]
okay thank you for help but i don't know what's going on with this edition of the line because in config it adds the city name and it doesn't show me
![image](https://user-images.githubusercontent.com/57010926/78462974-ddd52100-76d7-11ea-96ae-c104a476dfaf.png)
![image](https://user-images.githubusercontent.com/57010926/78462978-e62d5c00-76d7-11ea-8757-ca017cb64ad9.png)

**Comment by tobi132** [comment]
Remove or change 'sample town'

**Comment by cocaocla** [comment]
repaired thank you again for your help <3 you are great!
