### ISSUE TITLE
castle24 error

### ISSUE THREAD

**Issue by cocaocla** [slawkens/myaac#116]
hello, I need help Because mac has compatibility with gesior but when I add castle24 to templates who has it doesn't work
does anyone know how to fix it or how to add it? help anyone please

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/78590237-cdd95080-7841-11ea-8299-650a677fb69b.png)

**Comment by Leesneaks** [comment]
Can  you link the code you used?

**Comment by slawkens** [comment]
You have some error in your SQL statement.

Probably your database is not compatible with it, missing some columns or tables.

If you post some code, we can re-open this.
