### ISSUE TITLE
Bug Guild Create

### ISSUE THREAD

**Issue by lucasfaverzani** [slawkens/myaac#117]
### Server configuration
- Operating System: Windows Server 2012 x64
- Web Server (+ version): UniServer Zero XVIII
- PHP Version: PHP Version 7.1.1
- Server name and version (for example: TFS 0.3): TFS 1.3
- MyAAC Version: 0.8.1? Latest?

### Client configuration (Your Computer)

- Browser: Google Chrome
- Operating System: Windows 10 x64

### Description:
Backtrace:

#0 C:\UniServerZ\www\system\libs\pot\OTS_Guild.php(199): PDO->exec('INSERT INTO `gu...')
#1 C:\UniServerZ\www\system\pages\guilds\create.php(108): OTS_Guild->save()
#2 C:\UniServerZ\www\system\pages\guilds.php(30): require('C:\\UniServerZ\\w...')
#3 C:\UniServerZ\www\index.php(360): require('C:\\UniServerZ\\w...')
#4 {main}

### Steps To Reproduce:
Simple guild create

**Comment by gpedro** [comment]
can you attach some print screen?

**Comment by lucasfaverzani** [comment]
of course, here go.

![image](https://user-images.githubusercontent.com/63333213/78843135-5689f500-79d8-11ea-8595-2a1e730421cd.png)

**Comment by Leesneaks** [comment]
The error message tells you exactly what is wrong.
Your server has a lower thread_stack (128k) than what is required for mysql.
Mysql documentation shows a default value of 192k (196608) for 32bit and 256k (262144) 64bit systems.

You will need to change this in your server.
I haven't used uniform server but its documentation states:

"Location of the configuration file: UniServerZ\core\mysql\my.ini"
find thread_stack and update accordingly.

**Comment by lucasfaverzani** [comment]
ah ok, i've made this change and it fixed the problem
thanks for the good work

its solved.
