### ISSUE TITLE
sms shop error.

### ISSUE THREAD

**Issue by cocaocla** [slawkens/myaac#118]
hello, there is a problem with the sms shop, and more
forumito, after setting up and using the test does not add premium points,
everything passes successfully when completed correctly redirects to gifts, but premium points are still not on the account

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/79043204-1f952880-7bfe-11ea-9a01-7c2d4cef161c.png)
I have one more problem because I tried to do different sections, slawkens told me that I have to edit it in the dancyh database, but I edited and it doesn't show up after adding item, there is only one, not 4, can anyone help me?
![image](https://user-images.githubusercontent.com/57010926/79043252-6f73ef80-7bfe-11ea-9897-0cdbb201a6ec.png)

**Comment by cocaocla** [comment]
Please Help me :(

**Comment by cocaocla** [comment]
I can't handle it :( can anyone help? Please :(

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/79068938-bfb88380-7cca-11ea-876b-ab7fc8d3556e.png)
after editing the sms shop files, the result pops up, when adding, it is not displayed to enter the id and quantity
![image](https://user-images.githubusercontent.com/57010926/79068957-e37bc980-7cca-11ea-9b29-a05e2ffe2d28.png)
can anyone help me?

**Comment by slawkens** [comment]
Gesior shop plugin is very outdated, and I won't provide any support for it.

The new shop system has to be written.

And also this is the wrong repository to report this.
