### ISSUE TITLE
New Template

### ISSUE THREAD

**Issue by Qwizer** [slawkens/myaac#12]
Emma layout plizzz

**Comment by slawkens** [comment]
Hehe, you spam with it in every possible way.

Ok then, I will try to release Emma layout tomorrow.

**Comment by Qwizer** [comment]
I love you, and the most beautiful layout of my-acc

**Comment by slawkens** [comment]
So, here's your emma template released:
https://otland.net/threads/myaac-plugin-template-emma.254130/

**Comment by Qwizer** [comment]
link unavailable

**Comment by slawkens** [comment]
Yeah it hasn't been accepted yet. It will work once accepted.

**Comment by Qwizer** [comment]
:)
Thank you very much. 
I'm really enjoying my acc, congratulations.
