### ISSUE TITLE
Bug character page.

### ISSUE THREAD

**Issue by gabz182** [slawkens/myaac#120]
After you buy a house in the game, the following error appears

Notice: Undefined offset: 2 in C:\xampp\htdocs\system\pages\characters.php on line 397

https://prnt.sc/s212ta
OtservBr 12
Myacc last version.

**Comment by Leesneaks** [comment]
Have you set your config['towns'] in the config file?
That line of code, checks if house['town'] exists and then puts $config['towns'][$house['town']] into town on the array.
Also Is the house set to the correct town value same as in the map editor and config file..

**Comment by gabz182** [comment]
> Have you set your config['towns'] in the config file?
> That line of code, checks if house['town'] exists and then puts $config['towns'][$house['town']] into town on the array.
> Also Is the house set to the correct town value same as in the map editor and config file..

Ohh... ok!
I will check this.

**Comment by Leesneaks** [comment]
Did this resolve your issue?

**Comment by gabz182** [comment]
> Did this resolve your issue?

Yes bro!
Thanks!
