### ISSUE TITLE
two spaces in the name

### ISSUE THREAD

**Issue by malborobeck** [slawkens/myaac#121]
### Server configuration
- Operating System: 
- Web Server (+ version):  xampp
- PHP Version: 7.0
- Server name and version (for example: TFS 0.3): otx2 8.6
- MyAAC Version: last version
### Client configuration (Your Computer)

- Browser: 
- Operating System: 

### Description:
it is possible to create characters with two spaces in the name. Example: Maraleth  Edus

### Steps To Reproduce:

**Comment by malborobeck** [comment]
this ends up causing problems in the shop system, as it does not recognize characters with two spaces in the name.

**Comment by Leesneaks** [comment]
public static function characterName($name)

`if(preg_match('/ {2,}/', $name))
{
	self::$lastError = 'Invalid account name format. Use only A-Z and numbers 0-9 and no double spaces.';
	return false;
}`

**Comment by malborobeck** [comment]
It works in part, it displays the warning however it is still possible to create a character with 2 spaces in the name.

**Comment by Leesneaks** [comment]
Sorry the sourcecode.
I was working on at the time was a little outdated, the check needed to be added to system\libs\createcharacter.php as well.
This throws an error on the newest pull.
![image](https://user-images.githubusercontent.com/42119604/81329235-2779a880-9096-11ea-897f-c8f0d0bfcb22.png)

See my new commit.

**Comment by slawkens** [comment]
Closing, as seems to be resolved.
