### ISSUE TITLE
Error's when I create account 

### ISSUE THREAD

**Issue by Pi0tRuS** [slawkens/myaac#122]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''')' at line 1

Backtrace:

#0 /var/www/html/system/libs/pot/OTS_Base_DB.php(85): PDO->query('INSERT INTO `pl...')
#1 /var/www/html/system/libs/CreateCharacter.php(210): OTS_Base_DB->query('INSERT INTO `pl...')
#2 /var/www/html/system/pages/createaccount.php(271): CreateCharacter->doCreate('Sorc', 1, 1, 1, Object(OTS_Account), Array)
#3 /var/www/html/index.php(360): require('/var/www/html/s...')
#4 {main}

**Comment by slawkens** [comment]
What character name do you try to create? Maybe you use some weird characters?

Need more info.

**Comment by slawkens** [comment]
Are you going to provide us some details?

**Comment by slawkens** [comment]
Closing due to no feedback.
