### ISSUE TITLE
guild invite

### ISSUE THREAD

**Issue by rikemark** [slawkens/myaac#123]
Hi, 
this error occurs when i will invite a player to my guild:
![bug_invite](https://user-images.githubusercontent.com/47008729/81829893-c9bfe300-9511-11ea-8c8a-ac214760f5ff.png)

otservbr-global 12x (FTS)
phpmyadmin
last gesior

Thanks in advance.

**Comment by slawkens** [comment]
Where does it come from, the "date" column in guilds table?

I can't find it in otservbr-global

**Comment by Leesneaks** [comment]
I believe its the guild_invites table

`CREATE TABLE IF NOT EXISTS `guild_invites` (
  `player_id` int(11) NOT NULL DEFAULT '0',
  `guild_id` int(11) NOT NULL DEFAULT '0',
  `date` int(11) NOT NULL,`
