### ISSUE TITLE
sql injection

### ISSUE THREAD

**Issue by Olimpotibia** [slawkens/myaac#124]
Idont know how but have sql injection pls fix

**Comment by Leesneaks** [comment]
Hi, your post is very limited.
Please provide more information.
You haven't mentioned what version you are using or what has happened to know you have SQL injection.

Please provide full details so people can investigate.

**Comment by Olimpotibia** [comment]
in lostaccount.php

**Comment by Leesneaks** [comment]
If you want assistance you should provide the information that was requested.
What version are you using?
Are you sure its with lostaccount?

**Comment by Olimpotibia** [comment]
yes 100%

**Comment by Olimpotibia** [comment]
removed lostaccount.php from the website and no more problems

**Comment by Leesneaks** [comment]
Hi Olimpotibia,

Did you download the newest version of myaac from here and not a 3rd party website? and the newest master version?
What about your database, is it copied? fresh?? Have you secured it properly? Changed the root password etc?

I find it strange that there have been 7227 installations of Myaac (i know of one server which has over 800 players)  and only one report of a hacking from a server with 2 players (i am assuming you are xkeeOT as they had complained about injection)

Could you provide logs of the the attackers accessing the page, web logs should show what they accessed. Make sure you remove any IP addresses etc. you should be able to see web links ?lostaccount=name~
etc, you should have these if you can 100% assure its this page causing it.

Your post has very limited information to go by but if you could provide more information this can definitely be looked into, the more information of what step is causing it could help greatly.
.
A few people have checked the lostaccount and haven't found anything.
Thanks

Lee

**Comment by gabz182** [comment]
Hello @Leesneaks 

I don't know what this guy is talking about, but I know that some servers were facing a problem where a player was able to put "9999" coins for the lost account due to a bug, but this is on the Gesior website, I don't know about myacc.

`subtopic=>lostaccount;character=>Newba;step=>email2;email=>'; UPDATE accounts set coins = "9999" WHERE name = "xaxaxa123";;Submit_x=>0;Submit_y=>`

https://github.com/Riicksouzaa/TheRealGesiorFerobra/commit/473e9ff71c4a286831fc719c49e49aab559ad102

PS: I don't know how it works, I'm just trying to help.

**Comment by Leesneaks** [comment]
Hi gabz,
I really appreciate you taking your time to input on this.
After some more tests, I am still unable to replicate this issue through Myaac but will continue to look into it when I have time.
I have wanted to replace the querys with prepared PDO statements for a while so maybe for a newer versions these can be upgraded anyway as they are more secure.

**Comment by Olimpotibia** [comment]
too strange...

**Comment by slawkens** [comment]
Closing due to too less information provided.

We couldn't (together with @Leesneaks) find any proof for this kind of vulnerability.
