### ISSUE TITLE
Wrong mana of the samples characters

### ISSUE THREAD

**Issue by dudantas** [slawkens/myaac#125]
The mana of the chars sample is wrong, lvl 8 has 90 mana and the install is creating with 35 mana.

**Comment by slawkens** [comment]
Since when? AFAIK you become 5 mana per level as None Vocation. That is 7 * 5 = 35.

Also please specify which vocations :)

**Comment by slawkens** [comment]
Hi,

Ok seems you are right.

I checked it in the calculator here: https://tibia.fandom.com/wiki/Calculators

I will correct this once I'm home.

**Comment by dudantas** [comment]
Changed in version 10.50 ~~ more or less

Thanks for the attention
