### ISSUE TITLE
Broken coutmax and chance in item tooltip

### ISSUE THREAD

**Issue by gerotib** [slawkens/myaac#126]
After myaac updates I found that chances and coutmax are not shown in creature item tooltips anymore. I did some research and found that it broke after https://github.com/slawkens/myaac/commit/7424901acaee93cc68e83c0985ee46755b8522a1 commit.

![tooltip](https://user-images.githubusercontent.com/29408915/83059992-100d5a00-a05b-11ea-8f71-f686c6d0fb4e.png)

**Comment by slawkens** [comment]
Thanks for the info.

I fixed it in https://github.com/slawkens/myaac/commit/5250b3189b287048a710f78cc7f43174e30e8dee
