### ISSUE TITLE
Error creating new guild

### ISSUE THREAD

**Issue by sxbx23** [slawkens/myaac#127]
### Server configuration
- Operating System: Win10
- Web Server (+ version):  Uniform Server XIV
- PHP Version: 7.4.5
- Server name and version:  latest otservbr-global github version (tfs 1.3)
- MyAAC Version:  latest github version

### Description: 
does not let you create guild and gives an error message -> img https://prnt.sc/spitbw

### Steps To Reproduce:
1) Login in to your account
2) Go to the Guilds page
3) Press button "Found Guild"
4) Whrite a Guild Name
5) Press Submit
6) Error
### Installed Plu-gins
1) Tibia12 Login -> https://github.com/opentibiabr/myaac-tibia12-login
2) Welcombe Box -> https://github.com/slawkens/myaac-plugins/tree/master/welcome-box
3) Powerful Guilds -> https://github.com/slawkens/myaac-plugins/tree/master/powerful-guilds
4) My-acc template tibiacom

**Comment by sxbx23** [comment]
i got the same error in znote, gesior and myacc , I googled how to fix it and it worked , sorry for this noob issue , im just learning.

1) Open Uniform server
2) Go to "Mysql" -> "Edit config file my.ini"
3) In line 31 change "thread_stack = 128k" to "thread_stack = 256k"
4) done :P

**Comment by slawkens** [comment]
Glad you managed to fix it yourself.
