### ISSUE TITLE
remove Engine MyISAM

### ISSUE THREAD

**Issue by rcatechnology** [slawkens/myaac#128]
When we are using google cloud sql or another SaaS cloud, we couldn't set engine as MyISAM, instead the standard is InnoDB.

Most of the code is using InnoDB, but there's some files that are still using MyISAM. My suggestion is to change those files to InnoDB as well.
Files that I tracked down using linux:

/var/www/html/system/migrations/10 line: 16
/var/www/html/system/migrations/1 line: 13
/var/www/html/system/migrations/12 line: 25
/var/www/html/system/migrations/12 line: 37
/var/www/html/system/migrations/17 line: 15
/var/www/html/system/migrations/22 line: 14
/var/www/html/system/migrations/22 line: 23

**Comment by slawkens** [comment]
Hi,

Thanks for your report.

You are actually right, that MyISAM should have been removed a long time ago, I missed it somehow in my commits.

Will do this once I'm home.

Regards,
