### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by QuebradaZN** [slawkens/myaac#129]
when you are going to do the installation, after the first stage, it already causes this

Unable to create the cache directory (/var/www/html/system/cache/twig/b6).

https://prnt.sc/ssgswc

**Comment by Leesneaks** [comment]
Hi, if using linux, did you do everything in the installation information in.
https://github.com/slawkens/myaac/blob/master/README.md

 Note: Linux only
	If you're under linux use these commands to set proper permissions:
		chmod 660 config.local.php
		chmod 660 images/guilds
		chmod 660 images/houses
		chmod 660 images/gallery
		chmod -R 770 system/cache

**Comment by QuebradaZN** [comment]
Solved, the config.local.php file is missing
