### ISSUE TITLE
myaac_movie

### ISSUE THREAD

**Issue by QuebradaZN** [slawkens/myaac#130]
Can I get the complete database?

https://prnt.sc/staj7r

**Comment by slawkens** [comment]
Which version of MyAAC are you trying to install?

**Comment by QuebradaZN** [comment]
I think the most recent, I pulled this one from Git

**Comment by slawkens** [comment]
You can see version in Admin Panel

![image](https://user-images.githubusercontent.com/16687302/83695190-dfe52e80-a5f9-11ea-9680-1379d98c57c4.png)

**Comment by slawkens** [comment]
BTW. There is something wrong with your database, because migrations/2.php shouldn't be executed on newest versions.

**Comment by QuebradaZN** [comment]
Newer version installed, no installation errors, only when running the site
https://prnt.sc/stb7kf
https://prnt.sc/stb7g7
https://prnt.sc/stb6zz

**Comment by slawkens** [comment]
did you import the myaac database schema.sql manually to your database?

**Comment by QuebradaZN** [comment]
I did it 2 ways, imported it manually and did the installation / install

**Comment by QuebradaZN** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'body' can't have a default value


Backtrace:

#0 /var/www/html/system/libs/pot/OTS_Base_DB.php(85): PDO->query('ALTER TABLE `my...')
#1 /var/www/html/system/migrations/2.php(5): OTS_Base_DB->query('ALTER TABLE `my...')
#2 /var/www/html/system/migrate.php(10): require('/var/www/html/s...')
#3 /var/www/html/index.php(189): require('/var/www/html/s...')
#4 {main}

**Comment by slawkens** [comment]
If you imported manually, then you need to execute this in your phpmyadmin:
```SQL
UPDATE `myaac_config` SET `database_version` = 30;
```

**Comment by QuebradaZN** [comment]
Solved... Perfect! <3

**Comment by slawkens** [comment]
Sorry, my query was wrong.

That's the correct one:
```SQL
UPDATE `myaac_config` SET value = 30 WHERE name = "database_version";
```
