### ISSUE TITLE
Error on houses

### ISSUE THREAD

**Issue by yehia** [slawkens/myaac#131]
Hello, i have this error from otserv-global-12 (otserv.com.br)

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'guild' in 'where clause'

Backtrace:

#0 /var/www/html/system/libs/pot/OTS_Base_DB.php(85): PDO->query('SELECT * FROM `...')
#1 /var/www/html/system/pages/houses.php(149): OTS_Base_DB->query('SELECT * FROM `...')
#2 /var/www/html/index.php(341): require('/var/www/html/s...')
#3 {main}`

**Comment by slawkens** [comment]
This is very weird issue you having. Did you try to clean the cache?

Try setting this in your config.local.php, and tell me if the issue persists:

```
$config['env'] = 'dev';
```

**Comment by slawkens** [comment]
Hello,

This has been just fixed in https://github.com/slawkens/myaac/commit/fcff820858dca3e8d2692e9bfee27ea89c8b9727
