### ISSUE TITLE
Error in change email

### ISSUE THREAD

**Issue by malborobeck** [slawkens/myaac#132]
### Server configuration
- Operating System:  windows server 2012
- Web Server (+ version):  xampp
- PHP Version:  7.1
- Server name and version (for example: TFS 0.3):  otx2
- MyAAC Version:  latest

### Client configuration (Your Computer)

- Browser: google chrome
- Operating System: windows 10

### Description:
When I confirm the email exchange, this warning appears:
C:\xampp\htdocs\system\pages\account\change_email.php

print: https://imgur.com/DupvVaY

### Steps To Reproduce:

**Comment by slawkens** [comment]
Hello,

Thanks for detailed description.

I fixed it in https://github.com/slawkens/myaac/commit/d4222e98e604592a9453a8ccde8ad2d7c28b85eb
