### ISSUE TITLE
Change Guild description error

### ISSUE THREAD

**Issue by RDaruish** [slawkens/myaac#138]
I'm trying to change the guild description but I run into this error

![Screenshot_3](https://user-images.githubusercontent.com/44595782/92043210-037f5880-ed52-11ea-8af6-79242fadafe6.png)

**Comment by slawkens** [comment]
You need to install bcmath php extension

sudo apt-get install php-bcmath

**Comment by RDaruish** [comment]
It worked, thank you very much!
