### ISSUE TITLE
change group bug

### ISSUE THREAD

**Issue by daniofordon** [slawkens/myaac#139]
Hello. can't change group? this is probably a bug

https://i.imgur.com/1Id9C8k.png

it's empty there is nothing

**Comment by daniofordon** [comment]
after manually changing group in console something like this pops up

https://i.imgur.com/7QyJv0U.png

and something like that in the client

https://i.imgur.com/hNSbEdW.png

**Comment by slawkens** [comment]
We need more info.

1. What distribution? Otserv? TFS?

2. Do you have in your database table named "groups"?

3. Do you have file in your data folder named XML/groups.xml?

**Comment by daniofordon** [comment]
excuse me. my inattention. in xml there was no groups.xml :) best regards
