### ISSUE TITLE
Error Upload plugin

### ISSUE THREAD

**Issue by Qwizer** [slawkens/myaac#14]
The file you are trying to upload is not a .zip file. Please try again.

permissions applied and extensions loaded, linux debian 7.
- PDO PHP Extension
- XML PHP Extension
- ZIP PHP Extension
chown -R www-data.www-data /var/www/*
		chmod 660 config.local.php
		chmod 660 images/guilds
		chmod 660 images/houses
		chmod 660 images/screenshots

**Comment by slawkens** [comment]
Can you try to edit this file: system/pages/admin/plugins.php

Add:
`var_dump($type);`

After:
`$type = $file["type"];`

and tell me the output when you try to upload the file again?

**Comment by slawkens** [comment]
Try with latest version: https://github.com/slawkens/myaac/releases/latest

**Comment by Qwizer** [comment]
Thank you. I'll do the test.
