### ISSUE TITLE
Players Guild Ranks

### ISSUE THREAD

**Issue by Leesneaks** [slawkens/myaac#142]
### Server configuration
- Server name and version (for example: TFS 0.3):  1.3 OTBRSERV
- MyAAC Version: All previous versions

### Description:
I haven't had time to fix this but the player guild nicknames are broken for players.
It doesn't read them on player load it only reads them if they exist in players.guildnick
Line 159 OTS_Player       -   guildNick

**Comment by Leesneaks** [comment]
@slawkens 
https://github.com/slawkens/myaac/blob/develop/system/libs/pot/OTS_Player.php#L237
If 237 and 238 is removed or 238 set to null and not '' it fixes this issue.

getGuildNick on line 1886, won't call loadranks as guildnick is set to '' which is an empty string value which isset
https://github.com/slawkens/myaac/blob/develop/system/libs/pot/OTS_Player.php#L1886

I have commented it from test code but cannot see any issues on any of the pages.
Any suggestions or issues witht his change?

**Comment by slawkens** [comment]
Yes, lines 237 and 238 can be removed. Same with 240 & 241.

That seems to be the best solution.

Also this function needs to be adjusted:
```
    public function getRankId()
    {
        if( !isset($this->data['rank_id']) )
        {
            throw new E_OTS_NotLoaded();
        }

        return $this->data['rank_id'];
    }
```

To something like this:
```
    public function getRankId()
    {
	    if(!isset($this->data['guildnick']) || !isset($this->data['rank_id']))
		    $this->loadRank();

	    return $this->data['rank_id'];
    }
```

Also, I can't find any usage of OTS_Player:getGuildNick() in code, that's why I never came across this issue. Do you use it in your code?

**Comment by Leesneaks** [comment]
I noticed it when making the guild editor for the admin panel and noticed the issue on the guilds page whilst editing chars
Its called in guilds.view.html.twig L143 and shows a textbox to edit the guildnickname.

**Comment by Leesneaks** [comment]
This commit fix's this issue. of the guildnicks not showing
![image](https://user-images.githubusercontent.com/42119604/107877315-87be3600-6ec3-11eb-9806-3f444e0ee00b.png)
