### ISSUE TITLE
Parameter experienceStages in config.lua (in tfs engine) fails installation

### ISSUE THREAD

**Issue by jarekkowol** [slawkens/myaac#148]
```
experienceStages = {
	{ minlevel = 1, maxlevel = 8, multiplier = 7 },
	{ minlevel = 9, maxlevel = 20, multiplier = 6 },
	{ minlevel = 21, maxlevel = 50, multiplier = 5 },
	{ minlevel = 51, maxlevel = 100, multiplier = 4 },
	{ minlevel = 101, multiplier = 3 }
}
```

cause: syntax error, unexpected '{', expecting ';'

**Comment by Leesneaks** [comment]
You have failed to provide any information.
When submitting a new issue it shows you what you need to provide.
Server version?
MyAAC version?

Please provide more information than just it fails installation.

**Comment by slawkens** [comment]
@Leesneaks it's np.  I know the problem. In latest tfs they added some array into config.lua which our current (pretty weak) parser cannot parse. The solution would be to use some php library to parse lua files like this: https://github.com/KeldorDE/Lightweight-PHP-LUA-Parser

**Comment by Leesneaks** [comment]
I bypassed the error by putting it all on the same line as a temporary fix.
`experienceStages = { { minlevel = 1, maxlevel = 8, multiplier = 7 }, { minlevel = 9, maxlevel = 20, multiplier = 6 }, { minlevel = 21, maxlevel = 50, multiplier = 5 }, { minlevel = 51, maxlevel = 100, multiplier = 4 },	{ minlevel = 101, multiplier = 3 }}`

Can someone confirm with the latest version of tfs 1.3 that this works in game as well.

**Comment by slawkens** [comment]
Here's the fix: https://github.com/slawkens/myaac/commit/b389874a7ed88518bedffec9207d9826f694bccc

You can download master branch again.

This is just a temporary solution, in future we will also parse arrays in config.lua cause they may be usefull.
