### ISSUE TITLE
Deletion House Access List

### ISSUE THREAD

**Issue by aokisama** [slawkens/myaac#149]
### Server configuration
- Operating System: linux 
- Web Server (+ version): apache2 
- PHP Version: 7.4
- Server name and version (for example: TFS 0.3): otservbrglobal 
- MyAAC Version: 8.3

### Client configuration (Your Computer)

- Browser: chrome
- Operating System: windows 

### Steps To Reproduce:
1.Delete a character without leaving house first
2.Access list will stay the same

**Comment by Leesneaks** [comment]
This list is saved to the database when IOMapSerialize::saveHouseInfo() is called in the Map::save() function.
You could add a check to that function to check if player exists when the server saves it.

**Comment by slawkens** [comment]
It shouldn't be possible to delete character if he owns a house.  That would be the best option I think.

**Comment by Leesneaks** [comment]
![image](https://user-images.githubusercontent.com/42119604/106612183-bdc4f700-6560-11eb-8d8d-fa283b20fc51.png)
