### ISSUE TITLE
Function getItemNameById($id) doesn't work

### ISSUE THREAD

**Issue by MatCollier** [slawkens/myaac#150]
Seems like it's returning empty

```
foreach ($loot as $item) {
				$itemname = getItemNameById($item['id']);
				$tooltip = 'Item: ' . $itemname . '<br/>Chance: ' . round($item['chance'] / 1000, 2) . '%<br/>Max count: ' . $item['count'];

				echo '<img src="' . $config['item_images_url'] . $item['id'] . '.gif" class="item_image" title="' . $tooltip . '" width="32" height="32" border="0" alt=" ' . $name . '" />';
				$i++;
			}
```

I'm using current myaac version (downloaded here).

```
function getItemNameById($id) {
	require_once LIBS . 'items.php';
	$item = Items::get($id);
	return !empty($item['name']) ? $item['name'] : '';
}
```

The funcion on functions.php is ok. The lib items.php also ok.

This is what the website shows:

![firefox_DAdnCHXYmA](https://user-images.githubusercontent.com/50173479/106827749-c3f1cb00-6667-11eb-9b1e-c96282965e36.png)

**Comment by Leesneaks** [comment]
Are you using dev or master build?
Ensure you are reloading your items.xml and that it is loaded into cache/db (can't remember which version it was changed from Database to cache.
I had this issue when It wasn't updating the cache file so the id didn't' exist..

**Comment by MatCollier** [comment]
That worked, thank you a lot.

The issue can be closed.
