### ISSUE TITLE
Headline.php returns image with errors/doesn't work

### ISSUE THREAD

**Issue by MatCollier** [slawkens/myaac#152]
I believe something is wrong with headline.php.

To be sure, I downloaded the my aac again, today, and tested it without making any changes.

Still got the same error.

If I create a new page/change the name of a page to one that doesn't have a premade image yet, it'll fail to generate one.

Code on index.php:

```
<?php
	$headline = $template_path.'/images/header/headline-' . PAGE . '.gif';
	if(!file_exists($headline))
		$headline = $template_path . '/headline.php?t=' . ucfirst($title);
?>
```

Headline.php:

```
<?php
//require '../../common.php';

//$text = $_GET['text'];
/*
$page_file = BASE . 'pages/' . PAGE . '.php';
if(!@file_exists($page_file))
{
	$page_file = BASE . 'pages/custom/' . PAGE . '.php';
	if(!@file_exists($page_file))
		die('Page does not exists.');
}
*/
//$file = 'images/header/headline-' . PAGE . '.gif';
//if(!file_exists($file))
//{
	if(strlen($_GET['t']) > 100) // max limit
		$_GET['t'] = '';

	// set font path
	putenv('GDFONTPATH=' . __DIR__);

	// create image
	$image = imagecreatetruecolor(250, 28);

	// make the background transparent
	imagecolortransparent($image, imagecolorallocate($image, 0, 0, 0));

	// set text
	imagettftext($image, 18, 0, 4, 20, imagecolorallocate($image, 240, 209, 164), 'martel.ttf', utf8_decode($_GET['t']));

	// header mime type
	header('Content-type: image/gif');

	// save image
	imagegif($image/*, $file*/);
//}

// output image
//header('Content-type: image/gif');
//readfile($file);
?>
```

Images showing the error on Firefox and Chrome:

![chrome_qou6JRSdAx](https://user-images.githubusercontent.com/50173479/107305427-ba9aa100-6a61-11eb-9c9e-4266db4da1f9.png)
![firefox_tyUhl5ChFe](https://user-images.githubusercontent.com/50173479/107305430-bb333780-6a61-11eb-944c-bc4934d715d6.png)

**Comment by MatCollier** [comment]
I tried changing so that the image would be saved as a gif file.

And here it is how it's being generated:
![headline-sistemasir](https://user-images.githubusercontent.com/50173479/107366143-8d2f1100-6abc-11eb-92ab-9aabdc155346.gif)

**Comment by slawkens** [comment]
For me it works.

Do you have PHP-gd extension installed?

**Comment by MatCollier** [comment]
Yes it's installed... I just downloaded myaac again from zero to test it, without any changes, and it still doesn't work.

![notepad++_ZY0GltidZ3](https://user-images.githubusercontent.com/50173479/107846498-f2d41380-6dc2-11eb-9f3b-ee87ed490f2f.png)

**Comment by slawkens** [comment]
Try this script:

```php
<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);
	
	if(strlen($_GET['t']) > 100) // max limit
		$_GET['t'] = '';

	// set font path
	putenv('GDFONTPATH=' . __DIR__);

	// create image
	$image = imagecreatetruecolor(250, 28);

	// make the background transparent
	imagecolortransparent($image, imagecolorallocate($image, 0, 0, 0));

	// set text
	imagettftext($image, 18, 0, 4, 20, imagecolorallocate($image, 240, 209, 164), 'martel.ttf', utf8_decode($_GET['t']));

	// header mime type
	//header('Content-type: image/gif');

	// save image
	//imagegif($image/*, $file*/);
?>
```

Visit the file with browser window and see if there are any errors.

**Comment by MatCollier** [comment]
Here:

Warning: imagettftext(): Could not find/open font in D:\Programas\XAMPP\htdocs\templates\tibiacom\headline.php on line 19

**Comment by slawkens** [comment]
Do you have the font file martel.ttf in your tibiacom template folder?

**Comment by MatCollier** [comment]
If it's any help... I just installed Gesior's headline.php, and it works fine... I only had to add the "custom scripts" folder, with all it's content, and use their code. Should I send it here?

And yes, martel.ttf is in my tibiacom template folder:

![explorer_xcruSo6H9C](https://user-images.githubusercontent.com/50173479/107846849-da192d00-6dc5-11eb-849a-8c11bea8df68.png)

**Comment by slawkens** [comment]
Try this one and see if there are still any errors, or just empty output:

```
<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);
	
	if(strlen($_GET['t']) > 100) // max limit
		$_GET['t'] = '';

	// set font path
	putenv('GDFONTPATH=' . __DIR__);

	// create image
	$image = imagecreatetruecolor(250, 28);

	// make the background transparent
	imagecolortransparent($image, imagecolorallocate($image, 0, 0, 0));

	$font = getenv('GDFONTPATH') . '\martel.ttf';
	// set text
	imagettftext($image, 18, 0, 4, 20, imagecolorallocate($image, 240, 209, 164), $font, utf8_decode($_GET['t']));

	// header mime type
	//header('Content-type: image/gif');

	// save image
	//imagegif($image/*, $file*/);
?>
```

**Comment by MatCollier** [comment]
Empty output this time

**Comment by slawkens** [comment]
Then try this:

```php
<?php
	if(strlen($_GET['t']) > 100) // max limit
		$_GET['t'] = '';

	// set font path
	putenv('GDFONTPATH=' . __DIR__);

	// create image
	$image = imagecreatetruecolor(250, 28);

	// make the background transparent
	imagecolortransparent($image, imagecolorallocate($image, 0, 0, 0));

	$font = getenv('GDFONTPATH') . '\martel.ttf';

	// set text
	imagettftext($image, 18, 0, 4, 20, imagecolorallocate($image, 240, 209, 164), $font, utf8_decode($_GET['t']));

	// header mime type
	header('Content-type: image/gif');

	// save image
	imagegif($image/*, $file*/);
?>
```

**Comment by MatCollier** [comment]
This one worked! Nice!!! Thank you a lot @slawkens

**Comment by slawkens** [comment]
@MatCollier 

Can you confirm if it works for you if you replace

`$font = getenv('GDFONTPATH') . '\martel.ttf';`

with

`$font = getenv('GDFONTPATH') . DIRECTORY_SEPARATOR . 'martel.ttf';`

Because the solution I posted seems to not work on linux. But the second one do.

**Comment by MatCollier** [comment]
Yeah! Second one works just fine!!

**Comment by slawkens** [comment]
Thanks for the info! :)
