### ISSUE TITLE
syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by ReeCrema** [slawkens/myaac#154]
### Server configuration
- Operating System: Debian 9
- Web Server (+ version): 
- PHP Version: 
- Server name and version (for example: TFS 0.3): https://github.com/opentibiabr/otservbr-global
- MyAAC Version: Lastest

### Client configuration (Your Computer)

- Browser: Google Cloud VPS
- Operating System: Debian 9

### Description:
When I start install from the website after choosing a Client version he shows me that erros

`syntax error, unexpected '?', expecting variable (T_VARIABLE)

Backtrace:

#0 [internal function]: POT->loadClass('OTS_DB_PDOQuery')
#1 /var/www/html/system/libs/pot/OTS_Base_DB.php(26): spl_autoload_call('OTS_DB_PDOQuery')
#2 /var/www/html/system/libs/pot/OTS.php(316): include_once('/var/www/html/s...')
#3 [internal function]: POT->loadClass('OTS_Base_DB')
#4 /var/www/html/system/libs/pot/OTS_DB_MySQL.php(25): spl_autoload_call('OTS_Base_DB')
#5 /var/www/html/system/libs/pot/OTS.php(316): include_once('/var/www/html/s...')
#6 [internal function]: POT->loadClass('OTS_DB_MySQL')
#7 /var/www/html/system/libs/pot/OTS.php(373): spl_autoload_call('OTS_DB_MySQL')
#8 /var/www/html/system/database.php(98): POT->connect(Array)
#9 /var/www/html/install/includes/database.php(6): require('/var/www/html/s...')
#10 /var/www/html/install/steps/5-database.php(51): require('/var/www/html/i...')
#11 /var/www/html/install/index.php(216): require('/var/www/html/i...')
#12 {main}`

**Comment by slawkens** [comment]
What Php Version?

You can check this by writing in console:

php -v

**Comment by ReeCrema** [comment]
PHP 7.0.33-0+deb9u10 (cli) (built: Oct  6 2020 17:08:28) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u10, Copyright (c) 1999-2017, by Zend Technologies

**Comment by slawkens** [comment]
Upgrade your PHP to minimum 7.1, I have currently no other solution for this.

**Comment by ReeCrema** [comment]
I upgrade to 7.4 
```
PHP 7.4.15 (cli) (built: Feb 20 2021 05:33:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies
```
but still the same error...

I tryied do in my Local Machine (windows) and everything works...
I think its something because Google Cloud VPS... But I dont find the problem...

**Comment by slawkens** [comment]
You also need to update your apache2/nginx config to use that php version. This problem exist only on php version 7.0 and lower.

**Comment by ReeCrema** [comment]
Hello!
Sorry, do you have any tutorials or what I need to conf in apache2? 
I was looking, but I found nothing.

**Comment by slawkens** [comment]
Execute this in your terminal:

```
sudo a2dismod php7.0
sudo a2enmod php7.4
sudo service apache2 restart
```

**Comment by ReeCrema** [comment]
Worked !!!
Thanks man!
