### ISSUE TITLE
Error in Guild Manager page while deleting rank | SOLUTION

### ISSUE THREAD

**Issue by Misztrz** [slawkens/myaac#158]
Hello, everyone.
I noticed an error while deleting a rank in guild management page.
The error occurs if you try to remove a rank when a player has this rank.

 

> Uncaught Error: Call to a member function setRank() on array

So, the solution should be change this lines: **in system->pages->guilds->delete_rank.php around 80th line**
```
foreach($players_with_rank as $player_in_guild) {
	 $player_in_guild->setRank($new_rank);
	}
```

To this:

```
foreach($players_with_rank as $player_in_guild) {
	$player = new OTS_Player();
	$player->load($player_in_guild['id']);
	if ($player->isLoaded())
		 $player->setRank($new_rank);
	}
```

Thank you, taht's all. Have a nice day.

**Comment by slawkens** [comment]
Thanks! Committed into repo.
