### ISSUE TITLE
Pages created in the admin panel are not found (error 404)

### ISSUE THREAD

**Issue by MoisesFV** [slawkens/myaac#166]
### Description:

Pages created in the admin panel are not found (error 404)

### Steps To Reproduce:

Apparent problem in index.php. In previous versions the error does not occur.

Update: Error occurs after last commit(Security fix …

Don't allow slash in URL)

**Comment by slawkens** [comment]
Thanks, I'm aware of this.

The actual fix is here: https://github.com/slawkens/myaac/commit/a2a773d714509654d95f6b559c186db29ce1eafb

I'm waiting till tomorrow for feedback then I will release a fixed version.

**Comment by MoisesFV** [comment]
the error still persists

**Comment by slawkens** [comment]
> the error still persists

Did you applied all yesterday changes?

**Comment by MoisesFV** [comment]
Yes I replace 

`if(!@file_exists($file))` 

with the

`if(!@file_exists($file) || preg_match('/[^A-z0-9_\-]/', $page))`

**Comment by MoisesFV** [comment]
I removed:

`if(!$found) {
		$page = '404';
	}
	else {`

and it worked

**Comment by slawkens** [comment]
You don't need to remove anything, because it is already fixed.

You just need to be sure you are using the latest version.
