### ISSUE TITLE
BUG Online

### ISSUE THREAD

**Issue by CatDealers** [slawkens/myaac#167]
<!--
Please use this issue tracker only for reporting MyAAC bugs.

How to resolve online status. please help me?

Screenshots Link:
https://prnt.sc/1eenizd

13:55 115 player(s) online:

### Server configuration
- Operating System: Ubuntu 16.04
- Web Server (+ version): Loleslav version 1.1
- PHP Version: 7.0
- Server name and version (OTX2 2.15): 
- MyAAC Version: 0.8.6

### Client configuration (Your Computer)

- Browser: Chrome Google
- Operating System: Windows 7

**Comment by slawkens** [comment]
So, what's the bug? Or did you resolve your issue already.

**Comment by CatDealers** [comment]
I cannot resolve this status online. I've tried it sometimes. it didn't.
But could you help me online status code what the situation?
Code:
<?php
					if($status['online']){
					echo '<b>Players On-Line:<font color="yellow"><br>
					<b>'.$status['players'] . '/' . $status['playersMax'].'</font></b>
					<br>Uptime:<br></b>
					<b>'.$status['uptimeReadable'].'</b><br>';
					}else{
					echo '<br><font color="red">Server is Offline</font>';
					}
					?>

**Comment by slawkens** [comment]
There is nothing wrong with your code. Did you put it in <?php tags?

**Comment by CatDealers** [comment]
Code Link Here: [](https://pastebin.com/Z521Y90D)
it's not working It had 60 players. but in-game there are 120 players online. is there something wrong there?

**Comment by CatDealers** [comment]
https://pastebin.com/Z521Y90D

**Comment by slawkens** [comment]
It's showing what your server returns.

Maybe you have installed in your server code that doesn't count multiclients?

**Comment by CatDealers** [comment]
I haven't changed anything, is it a problem to be the php code online or does it depend on the server?

**Comment by CatDealers** [comment]
My server is current otx2, there is no problem online. depends what php code will be? less of this can help code situation which is the wrong or certain form code. just tell me?

**Comment by slawkens** [comment]
There is nothing wrong with the php code.

It displays that what your server says.

So you need to edit your server status.

**Comment by slawkens** [comment]
Closing, as not related to AAC code, but server code.
