### ISSUE TITLE
$player->getStorage() does not work at all

### ISSUE THREAD

**Issue by gesior** [slawkens/myaac#169]
### Server configuration
- Operating System: any
- Web Server (+ version): any
- PHP Version: any
- Server name and version (for example: TFS 0.3): any
- MyAAC Version: any

### Description:

**$player->getStorage()** always returns **NULL** (+ sometimes notice about accessing bool as array)

In this line:
https://github.com/slawkens/myaac/blob/master/system/libs/pot/OTS_Player.php#L2492
```
!==
```
should be:
```
===
```

**Comment by slawkens** [comment]
Thanks.
