### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Qwizer** [slawkens/myaac#18]
debian 7, othire

empera.online não consegue atender a esta solicitação no momento.
HTTP ERROR 500

**Comment by Qwizer** [comment]
chown -R www-data.www-data /var/www/*
		chmod 660 config.local.php
		chmod 660 images/guilds
		chmod 660 images/houses
		chmod 660 images/screenshots
installation successful

**Comment by slawkens** [comment]
Can you check what's in your php.log? Its in /var/log/apache2/error.log

Simply do in command line:
cat /var/log/apache2/error.log

**Comment by Tetee11** [comment]
i had this error after the step: configuration

this is my log
`[Wed Oct 11 15:12:22.359265 2017] [php7:crit] [pid 6956:tid 1940] [client ::1:6240] PHP Parse error:  syntax error, unexpected '--' (T_DEC), expecting ';' in C:\\Users\\Admin\\Documents\\UniServerZ\\www\\system\\functions.php(1186) : eval()'d code on line 1, referer: http://localhost/install/
`

**Comment by slawkens** [comment]
Show me your config.lua

You can paste it on pastebin.com

Remember to remove sensitive data like mysqlPassword.

**Comment by Tetee11** [comment]
I tested in OTX 2 and OTHire
this are the config.lua of both
```

https://github.com/mattyx14/otxserver/blob/otxserv2/path_7_x/config.lua (obviously I had it sqlType="mysql")

https://github.com/TwistedScorpio/OTHire/blob/master/config.lua
```

**Comment by Qwizer** [comment]
[Wed Oct 11 17:05:54 2017] [error] [client 177.5.192.97] PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/index.php on line 45

**Comment by slawkens** [comment]
@Qwizer Update your MyAAC to latest version.

@Tetee11 I've fixed this bug. Download latest version.

Link to latest version: https://github.com/slawkens/myaac/archive/master.zip

**Comment by Qwizer** [comment]
![image](https://user-images.githubusercontent.com/9012031/31468308-a1cb660e-aeb3-11e7-82f9-4b4884900f3e.png)
![image](https://user-images.githubusercontent.com/9012031/31468369-dfc7795c-aeb3-11e7-8ea6-578c8f350df9.png)
No error
![image](https://user-images.githubusercontent.com/9012031/31468379-eb71e792-aeb3-11e7-9f78-1ab56904dc7b.png)
admin panel 100%
![image](https://user-images.githubusercontent.com/9012031/31468427-2bfb535c-aeb4-11e7-93eb-dbf49d9f0443.png)

**Comment by Tetee11** [comment]
Working 100%

**Comment by slawkens** [comment]
@Qwizer 
Uncomment in your index.php:
_// uncomment if your php.ini have display_errors disabled and you want to see errors_

and also 3 next lines. remove '//'.

**Comment by Qwizer** [comment]
@slawkens removed, no error
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by Qwizer** [comment]
I'll format the dedicated and install

**Comment by Qwizer** [comment]
last version
![image](https://user-images.githubusercontent.com/9012031/31527430-8b11528e-afa3-11e7-99bc-2961bafa1c88.png)

**Comment by Qwizer** [comment]
line 45 and 46

if(!empty($page))
	$uri = str_replace('/', '', $uri);

work 
![image](https://user-images.githubusercontent.com/9012031/31528024-6a3528c0-afa7-11e7-804e-7792cf473efe.png)

**Comment by slawkens** [comment]
You were right. That error occurred on PHP versions lower than 5.5, and you have 5.4 so you were the case.

I fixed it by changing that line you posted, from:
`if(!empty(BASE_DIR))`

To:
`$tmp = BASE_DIR;
if(!empty($tmp))`
