### ISSUE TITLE
TFS Webservice

### ISSUE THREAD

**Issue by omarcopires** [slawkens/myaac#180]
Well, as everyone already knows, support for protocol 12.72 was added to TFS, with that came the need to add login.php to be able to connect to the server and currently MYAAC doesn't have this plugin, anyway I'm trying to work on it to make connection, but still not successful.
Here's the code base I've been working on:
https://gist.github.com/omarcopires/b5bfa3febd5a7f4601fc08dd84597843

I believe the problem is sessionkey related.

**Comment by lgrossi** [comment]
https://github.com/opentibiabr/login-server 😘

**Comment by slawkens** [comment]
> https://github.com/opentibiabr/login-server 😘

That might be helpful as reference, thanks. 

#topic
Did you test the version from otservbr team? There was some repo they had with myaac login plugin for version 12.x, maybe it works with tfs 12.x too? I'm currently unable to test.

**Comment by omarcopires** [comment]
@slawkens the login that I put in for example is basically the same as theirs, with the exception that boosted, events and the premium system were removed, which was also custom.
I changed the tables to be compatible with tfs, but I still couldn't connect, not even using the login without edits.
As said, I believe it's something related to sessionkey,
well, we can see an example of the changes here: https://github.com/Znote/ZnoteAAC/pull/493

**Comment by gpedro** [comment]
well, idk about that issue... but opentibiabr already made a plugin for tibia12
https://github.com/opentibiabr/myaac-tibia12-login

it's the most used plugin for myaac
https://my-aac.org/charts/

--

there are not many changes, opentibiabr looks better than yours, but you can feel free to make a pull request to make some compatibility, like table and column existence

**Comment by slawkens** [comment]
I am unsure if login service should be part of AAC, that's the first thing.

Second, the plugins always existed as @gpedro pointed.

So I'm closing this now, because discussion is useless.

**Comment by slawkens** [comment]
Thanks for closing, feel free to reopen if you have any further questions.
