### ISSUE TITLE
Login.php plugin [Network error - Connection::parseHeader] Invalid Client Login

### ISSUE THREAD

**Issue by Mesosot** [slawkens/myaac#19]
login.php not working
i get this error
[Network error - Connection::parseHeader] Invalid Client Login

**Comment by slawkens** [comment]
Which IP Changer, and what Client version are you using?

**Comment by slawkens** [comment]
Please try the latest version posted here:
https://otland.net/threads/myaac-plugin-login-php-for-tibia-11.254389/#post-2469531

**Comment by Mesosot** [comment]
i did , also i written to you a reply , there ... 
its not working at all ...
i need to use your acc its more better than others

**Comment by Mesosot** [comment]
i really like the admin panel with the plugins styel 
if u need to try it ur self tell me i can help u
