### ISSUE TITLE
Account manager layout bug

### ISSUE THREAD

**Issue by Qwizer** [slawkens/myaac#20]
![image](https://user-images.githubusercontent.com/9012031/31671887-c55b5cd4-b339-11e7-99df-ba81cae8ee78.png)
tibiacom 100%
![image](https://user-images.githubusercontent.com/9012031/31671966-f69e6f70-b339-11e7-9248-a83fdb914191.png)

**Comment by slawkens** [comment]
Its not a bug, its a feature :P

I've changed default account management template for kathrine. I want to standardize templates and remove all original elements in it.

If you want to use same account management that you got on your tibiacom template, then copy templates/tibiacom/account.management.html.twig to templates/kathrine/
