### ISSUE TITLE
Spells error

### ISSUE THREAD

**Issue by kukas9** [slawkens/myaac#21]
Hello, I wanted to thank you for the project you have, it's great, I would ask you to help me, the site is conflicting with my Tibia, it is getting spells from the site, not server spells (spells.xml), I removed the spells table, and the spells.php, because it was entering spells that had nothing to do with the vocations, but even so he is taking other spells that are not yet true, can you help me solve this?

**Comment by slawkens** [comment]
Which version are you using?

**Comment by kukas9** [comment]
I am using the version of MyAAC 0.6.1, my tibia is derived (Naruto), TFS 0.4, protocol 8.60

**Comment by kukas9** [comment]
Sorry for the delay in answering, I did not think I would answer right away.

**Comment by kukas9** [comment]
You would go*

**Comment by slawkens** [comment]
What is your spells page looking like? Can you post screenshot?

And post also your vocations.xml file.

And explain more, what's wrong with it. Cause spells are loaded normally from spells.xml from your server_path.

**Comment by kukas9** [comment]
Good morning, all right, in relation to the server getting messy in spells was resolved by setting in config.php the server_path too, now in the spells. 
The first image (https://prntscr.com/gzrgmt) shows the spells of Madara and spells that are not him, tried two ways fix, first remove the spells that have the vocation ID 0, worsened the situation, 2nd - set all vocations that are with id 0, for your monsters, because the monsters have spells and he's linked on spells.xml, still continued the problem, the second picture shows the amount of vocations(https://prntscr.com/gzrgn2), due to talkaction "transform", changed to "!saga"(https://prntscr.com/gzrgmp), you can select the clothes that you want by entering the number (1, 2, 3, 4, etc.), to let optimized vocations.xml, both paths to solve affected the server, and the site even more complicated, I thought to myself, to avoid this situation a bit "boring", in this image sets the situation to resolve, the Box where you select the vocations, take only those that do not have duplicate name using GROUP BY, and a WHERE vocation (where is the name) > = 1 in the site he "transforms" the id in the name, for visual effect it returns the name but stores the ID, I think that's,  only ended up more confused where to find this code to try to optimize it, because the only way that does not affect the server would be this way (https://prntscr.com/gzrgn2),  After that I became even more confused and came to ask your help

**Comment by slawkens** [comment]
I need your spells.xml file and vocations.xml to have more information.

Send them here: https://pastebin.com/

Or send me per email if you don't want to paste them public: slawkens@gmail.com

**Comment by kukas9** [comment]
i Send email!

**Comment by kukas9** [comment]
Version 0.6.5 MyAAC, have system SHOP?
