### ISSUE TITLE
drop eval function

### ISSUE THREAD

**Issue by gpedro** [slawkens/myaac#213]
### Description:

drop `eval` functions for better support on running in web hosting

- https://github.com/otsoft/myaac/search?q=eval&type=

**Comment by slawkens** [comment]
Any replacement suggested? ;)

**Comment by SRNT-GG** [comment]
Using proper functions and stuff would be good, I'll quote Rasmus (found of php, make of it what you will);
If eval() is the answer, you're almost certainly asking the
wrong question. -- Rasmus Lerdorf, BDFL of PHP

**Comment by slawkens** [comment]
In that case, this is _legit_ i think.

We have no user input there, just config.lua parsing.

But, well. I am open to suggestions how that could be replaced :)

**Comment by SRNT-GG** [comment]
> In that case, this is _legit_ i think.
> 
> We have no user input there, just config.lua parsing.
> 
> But, well. I am open to suggestions how that could be replaced :)

Currently looking iinto this, but seems eval() is only used to validate a expression exists and contains two values. This could be done with a if/switch statement instead. Could you elaborate on wheter or not I am missunderstanding this?

Will have a look into "fixing" this later when I have more time to test it's functionallity and then create a PR.

**Comment by gesior** [comment]
> In that case, this is _legit_ i think.

In Gesior2008/2012 - MyAAC base - it's only used to process `config.lua` of server (values defined by server owner).
I've not found any library to process Lua config in PHP, so I've made my own code to do it.

Ex. from TFS 1.4+ ( https://github.com/otland/forgottenserver/blob/master/config.lua.dist#L13 ):
```lua
timeToDecreaseFrags = 24 * 60 * 60
```
we need function that will return `86400` for this, but this is simple example.

For old servers like TFS 0.3.6 ( https://github.com/peonso/forgottenserver036pl1/blob/master/config.lua#L29 ) we need function that will return `10` for `monthlyFragsToBlackSkull`:
```lua
	monthlyFragsToRedSkull = 10
	dailyFragsToBlackSkull = dailyFragsToRedSkull
	weeklyFragsToBlackSkull = weeklyFragsToRedSkull
-- for this line
	monthlyFragsToBlackSkull = monthlyFragsToRedSkull
```
simplest solutions was to add some `$` and `;` to .lua file and process it as PHP file with `eval`.

**I THINK IT CAN BE CLOSED.**
Unless someone is interested in writing PHP code to parse Lua config files.

// OFFTOP: example 2 with 0.3.6 `config.lua` probably won't work in MyAAC as it process Lua `eval` on single line variables, not whole file as Gesior2021 does: https://github.com/gesior/Gesior2012/blob/master/classes/configlua.php

**Comment by slawkens** [comment]
Hi @gesior 

This second example with 0.3.6 - it is also possible in myaac, because it has this part of code from your AAC:
```
foreach($result as $tmp_key => $tmp_value) // load values definied by other keys, like: dailyFragsToBlackSkull = dailyFragsToRedSkull
$value = str_replace($tmp_key, $tmp_value, $value);
```

What's even more interesting - I also added a "dofile" parser, so it parses child-lua files (I used it in old days to organize config.lua into smaller pieces)

Anyway, you are right. I think we may close this issue as 1) we have not a real replacement and 2) we are parsing just owners config.lua

**Comment by gesior** [comment]
> This second example with 0.3.6

I must say that I deny any - commercial - MyACC work on Discord for yeeears.
I know PHP 5-7-8, Twig (Symfony) and Blade (Laravel), but I often got no idea what MyAAC does with some random 'modules', so I quit job on MyAAC.

**I'm pretty sure this issue should be closed.**

Some people may say that MyAAC is 200X code, but it's still is what most of OTS PHP programmers understand. Basic IFs, super basic routing (or no routing on Gesior2012).

I'm working on new acc. maker (Gesior202X), but when I release it probably nobody will use it. It will be probably only for 500+ online OTSes :(
