### ISSUE TITLE
removing log errors in some browsers

### ISSUE THREAD

**Issue by KOLISAO** [slawkens/myaac#225]
sorry. I'm too lazy to create a pull.

Error LOG:
`Uncaught TypeError: Cannot read properties of null (reading 'lastIndexOf')`

**correction:**
In templates/tibiacom/index.php, change:
`if(menus.lastIndexOf("&") === -1)`
to:
`if(menus.lastIndexOf("&") == -1)`

**Comment by slawkens** [comment]
Can you elaborate more? At least browser version would be useful.

If the menus object is null, that means the previous function call, which is:
```menus = localStorage.getItem('menus');```

Returned null. But why?

We can reproduce it, when we set following code
```menus = null;```

And after applying your fix, it doesn't change anything, the error is still here.

I suppose in your case - some javascript code failed to execute, and menus couldn't be saved, which happens on page unload.

Does this fix fixes the issue for you?
```
if(menus == null || menus.lastIndexOf("&") === -1) {
```
Sorry had no time to look at this before.
