### ISSUE TITLE
Account Status

### ISSUE THREAD

**Issue by Mesosot** [slawkens/myaac#23]
i get wrong account status while its premmy i get it as a free acc
Account Status: | Free Account

**Comment by slawkens** [comment]
What is your server distribution? Does it show in game that you have premium?

Also, its not enough to change 'premdays' in database, you also need to change 'lastday' field to last day of premium account.

**Comment by Mesosot** [comment]
Yes it shows its a premium in client and also gesior acc it see its premmy and it count good 
I tryed myacc it shows it free ,,,
About the database it inserted automatically while instalation ! Yes ?
I use malcoo otx server 11.48

**Comment by slawkens** [comment]
Are you sure you're changing it in good database?

I can't see anything wrong in code. It works fine on my otxserver 11.48.

**Comment by Mesosot** [comment]
I tryed it on a fresh database im sure

**Comment by slawkens** [comment]
This is the part of code that checks if you have premium:
`return $this->data['lastday'] > time();`

So, are you sure that in database, field accounts.lastday is bigger than time() (current time)?

**Comment by Mesosot** [comment]
last day = 0

**Comment by slawkens** [comment]
When you login to game then lastday gets updated from premdays. Set premdays to X (10 for example) and then login to game.

**Comment by Mesosot** [comment]
and?
![untertertertitled](https://user-images.githubusercontent.com/32135023/31837157-9ace9210-b58c-11e7-9f73-08f93327b75c.png)
![untirtyrtyrtytled](https://user-images.githubusercontent.com/32135023/31837199-beb0b474-b58c-11e7-9460-d025eb5fefc5.png)

**Comment by slawkens** [comment]
Ok you were right.

I fixed it in latest release.

Download here: https://github.com/slawkens/myaac/releases/latest

**Comment by Mesosot** [comment]
Awesome dude ;) u the best

**Comment by Mesosot** [comment]
Oh 1 more thing, when i add shop plugin 
It dont appear in the menu... it should added automatically???

**Comment by slawkens** [comment]
You need to add in config.local.php:
`$config['gifts_system'] = true;`

**Comment by Mesosot** [comment]
Cant it be installed or added automatically when installing the plugin ?

**Comment by slawkens** [comment]
Can be. Maybe I will add it in some version.

**Comment by Mesosot** [comment]
Keep it in mind mate
