### ISSUE TITLE
Guild Accept Invite Does Not Work

### ISSUE THREAD

**Issue by PsyManTV** [slawkens/myaac#232]
### Server configuration
- Operating System: Windows Server 2012 R2
- Web Server (+ version): XAMPP V3.3.0
- PHP Version: 
- Server name and version (for example: TFS 0.3): Tibia 13.x Canary
- MyAAC Version: Latest

### Client configuration (Your Computer)

- Browser: Chrome
- Operating System: Windows 10 x64

### Description:
When the player is invited to the guild on the website, his name appears on the invited list, but when he loggin in his account on the website, he cant see the accept invitation button, it only shows Leave Guild, but the player inst on the guild yet, and even if you press the Leave Guild button, it just dont work, return a msg "Any of your characters can't leave guild."
Its showing Leave Guild instead Accept Invitation.

### Steps To Reproduce:
Criate Guild > Invite Character > Loggin in the Invited Account > Acess Guild Page on Site > It does not show a accept invitation button only Leave Guild.

![image](https://github.com/slawkens/myaac/assets/142127744/7d56d94a-2f00-4f1a-a917-9c8164f175a5)

![image](https://github.com/slawkens/myaac/assets/142127744/cb0f2a00-16b2-4383-8200-85a173c72313)

 * @package   MyAAC
 * @author    Gesior <jerzyskalski@wp.pl>
 * @author    Slawkens <slawkens@gmail.com>
 * @author    whiteblXK
 * @copyright 2019 MyAAC
 * @link      https://my-aac.org

**Comment by slawkens** [comment]
Hi,

You are not using latest version of myaac - to get the last one go here: https://github.com/slawkens/myaac/releases
