### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by psmoros** [slawkens/myaac#234]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ouuan) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by slawkens** [comment]
Hello,

I will create that file, but currently don't have time.

You can send details to: security@my-aac.org

**Comment by ouuan** [comment]
Hi @slawkens, I see that you have fixed the vulnerabilities. Please review & publish the report on huntr.dev. Thank you!

**Comment by slawkens** [comment]
Hi,

So I have added SECURITY.md file into the repo.

I also published the report on your site.

So its time to close this one.

Sorry for late reply!
