### ISSUE TITLE
guildwar page error

### ISSUE THREAD

**Issue by realebra74** [slawkens/myaac#238]
Exception class: Error()

Call to undefined function getGuildLogoById()

File: /var/www/html/plugins/guild-wars/init.php
Line: 37

Backtrace:

#0 /var/www/html/system/pages/wars.php(15): displayGuildWars()
#1 /var/www/html/index.php(362): require('/var/www/html/s...')
#2 {main}

**Comment by slawkens** [comment]
Guild wars works only with develop branch of MyAAC, which is currently 0.10.x.

The getGuildLogoById function is there.
