### ISSUE TITLE
Cannot find config.lua

### ISSUE THREAD

**Issue by Aerwix** [slawkens/myaac#239]
I asked support on OTBR discord and my messages just got deleted, so I came here to ask support since you are the creator :P

Okay so, Im running a fresh installation in Ubuntu 22.04 and everything was fine until the localhost/install part.

For a strange reason Im getting this message on both verisons (OTBR and yours) so I believe It's something I did wrong.

![image](https://github.com/slawkens/myaac/assets/26527255/24e54762-dfa8-4fb2-b942-016a54178c73)

- I changed config.lua credentials and tested phpmyadmin connection. 
- Gave permissions that were needeed.
- My server is located on /home/funeralot/canary but I'm having some doubts now bc it never recognized 😵

**Comment by Aerwix** [comment]
Thanks for your suggestions, I gave up and installed everything on windows.

I will install virtual box and test it again bc I was using a paid vps so I cancelled :P

**Comment by zboinek** [comment]
> Hello! I don't know if you managed to fix it, but I had your same problem. I just had to use the following commands:
> 
> ```shell
> sudo chmod +x /home
> sudo chmod +x /home/user
> sudo chmod +x /home/user/canary
> sudo chmod +x /home/user/canary/config.lua
> ```
> 
> After that, the installation helper did work.

+x gives execute capabilieties to given dir or file. So it definitely isn't good way to go. I think, php user doesn't have permissions to access those files
