### ISSUE TITLE
?account/create

### ISSUE THREAD

**Issue by mlodzian4646** [slawkens/myaac#24]
I have a problem when setting up a new account.
The white page with error 500 is displayed

**Comment by slawkens** [comment]
Using latest 0.6.5 Version?

Can you post your apache error.log?

**Comment by Riicksouzaa** [comment]
see chmod privileges

**Comment by slawkens** [comment]
As stated here: https://otland.net/threads/myaac-v0-7-0.251454/page-16#post-2476511

Its probably caused by changing account_premium_days to anything higher than 0.

I will look into this today.

**Comment by slawkens** [comment]
This has been fixed in 3e49ef42a2d9e0b8e2f8a76f6eaf2ab035e37876
