### ISSUE TITLE
Bug in forum

### ISSUE THREAD

**Issue by dguprado** [slawkens/myaac#241]
I create a new board in the forum and all replies are shown with the name of the board author.
i am running a canary server 3.1.2 on windows server 2012

i am using the last rev of myaac from https://my-aac.org/

![bug forum](https://github.com/slawkens/myaac/assets/151960974/1cd5fa7b-e327-4696-91ad-1621015c0a84)

**Comment by slawkens** [comment]
I cannot reproduce that. Are you sure you using official version from https://github.com/slawkens/myaac

or maybe you using opentibiabr version as its canary? https://github.com/opentibiabr/myaac

**Comment by slawkens** [comment]
I cannot reproduce this. Any tips?

**Comment by dguprado** [comment]
This happens when you mix files from your repository with files from the tibiabr repository. I managed to resolve this issue by restoring 90% of my site to your repository. I believe this is a problem related to the tibiabr repository.

**Comment by slawkens** [comment]
Ye that sound reasonable. I will close the issue then as its not related to this repo.

Feel free to reopen if you feel the issue exist on my repo.

**Comment by dguprado** [comment]
Slawkens How do I install the pagseguro plugin? Do I need to place a file in the htdocs folder for pagseguro to communicate?

**Comment by slawkens** [comment]
> Slawkens How do I install the pagseguro plugin? Do I need to place a file in the htdocs folder for pagseguro to communicate?

The pagseguro plugin doesn't work anymore, cause they changed the API.
