### ISSUE TITLE
Online status

### ISSUE THREAD

**Issue by zboinek** [slawkens/myaac#242]
I can't find this answer anywhere. Which service 
- login HTTP
- login GRPC
- world

should be pointed in config.php to show online status?

**Comment by slawkens** [comment]
There are 4 variables in config.php for status:
```php
	'status_enabled' => true, // you can disable status checking by settings this to "false"
	'status_ip' => '',
	'status_port' => '',
	'status_timeout' => 2, // how long to wait for the initial response from the server (default: 2 seconds)
```

If you mean the port, then it should be set to 7171 (standard).

And IP can be set to '127.0.0.1'

**Comment by zboinek** [comment]
Ok, so it's game world port. I'm developing it in docker-compose so can't be set to localhost ;) Thanks for an answer

**Comment by zboinek** [comment]
It's probably not a case for an issue. It's my mistake somewhere but as I can see even setting it to false shows Server OFFLINE in top right corner :/
![image](https://github.com/slawkens/myaac/assets/13182568/d3f0bde5-fcb6-4632-92da-7bfe2e1bd2bd)

**Comment by slawkens** [comment]
You may want to look into mine docker setup: https://github.com/slawkens/myaac/pull/236

I set there the ip to `ip = "192.168.176.1"` in config.lua

**Comment by zboinek** [comment]
In files I can see that status is made from some socket response, but is there a way to debug status from curl maybe?
Is it your IP of docker machine? It looks like gateway

**Comment by slawkens** [comment]
You can't debug with curl, because its custom protocol AFAIK. It responds with XML however.

Yes its IP of the docker machine. But I think every Docker user will have different IP for their container. That one was from my setup.

**Comment by zboinek** [comment]
Yeap. But if you bind IP of container to host you can use it as a local IP. Any way, something else is broken in my setup :P As I can see number of players if serwer is online is taken from data base. I put true as default and now I can see that there is always 0 players, but if I click I can see of online folks :p strange

**Comment by zboinek** [comment]
hmm, that's strange. I bet that server info is some kind auto populated from files?
![image](https://github.com/slawkens/myaac/assets/13182568/329535fe-df19-44a4-9f14-313dc25d502b)
Name is correct because I didn't change it but all the rest is wrong

**Comment by slawkens** [comment]
serverInfo is populated from config.lua

It will be probably removed in future versions or moved to admin panel.

Anyway, I am closing this, as initial issue has been probably resolved (?).
