### ISSUE TITLE
Error while create new character

### ISSUE THREAD

**Issue by juniorerivaldo** [slawkens/myaac#246]
### Server configuration
- Operating System: ubuntu 22.04
- Web Server (+ version):  nginx
- PHP Version: 8.1
- Server name and version (for example: TFS 0.3): tfs 1.5 nekiro
- MyAAC Version:  last version -> main branch

### Client configuration (Your Computer)

- Browser: chrome
- Operating System: ubuntu 22.04

### Description:
when i create new character the website goes to blank page with HTTP ERROR 500
in database the new character not be created,
when i  install myaac the samples not come with instalation, i put manually on db.
need help.

### Steps To Reproduce:

**Comment by slawkens** [comment]
Would be useful if you could post the error from /var/log/nginx/error.log

**Comment by juniorerivaldo** [comment]
hi, sorry for delay, my nginx not generate any errors :(

**Comment by slawkens** [comment]
Then edit config.local.php

And set

$config['env'] = 'dev';

And then create character again. You should see the error message.

**Comment by slawkens** [comment]
Any news?

**Comment by juniorerivaldo** [comment]
sorry, it works i forgot to close issue . tnks for help
