### ISSUE TITLE
The requested URL /admin/?p=gifts was not found on this server.

### ISSUE THREAD

**Issue by ModernOTS** [slawkens/myaac#249]
Server configuration

    Operating System: Ubuntu 20.04 LTS
    Web Server (+ version): Apache/2.4.41
    PHP Version: v7.4.3-4ubuntu2.19
    Server name and version: TFS 0.3
    MyAAC Version: Myaac v0.8.14

Client configuration (Your Computer)

    Browser: tested in Firefox, Mircosoft Edge, Chrome(android)
    Operating System: Windows 10, Android

Description:
![obraz](https://github.com/slawkens/myaac/assets/155858437/ca81d573-920f-4c03-b4b9-418285cf80e0)
![obraz](https://github.com/slawkens/myaac/assets/155858437/34527905-955f-483c-9cc1-325a41867ddd)
![obraz](https://github.com/slawkens/myaac/assets/155858437/e92f1d7f-3648-46be-8466-ed55b0dc0e51)

I have problem with gesior shop "gift" page, buying works but i dont see any table in database and its impossible to add more products. 
i downloaded newest github version and compiled.
other problems is with guilds, its doesn't possible to upload guild logo, i using 900b 64x64 jpg image.

by the way, the question is, how to add other payment methods, e.g. Stripe, Skrill?

**Comment by slawkens** [comment]
1) About shop: what version of the plugin? You can view that in plugins/gesior-shop-system.json

2) do you have file admin/pages/gifts.php? Its included in the plugin by default.

3) About guild logo: probably no rights to save the file.

Did you execute following command to set user to www-data?

    sudo chown -R www-data.www-data /var/www

4) Stripe is already there, skrill maybe in the future.

**Comment by ModernOTS** [comment]
> 1. O sklepie: jaka wersja wtyczki? Możesz to zobaczyć w wtyczkach/gesior-shop-system.json
> 
>     2. Masz plik admin/pages/gifts.php? Domyślnie jest zawarty w wtyczce.
> 
>     3. O logo gildii: prawdopodobnie nie ma prawa do zapisywania pliku.
> 
> 
> Czy wykonałeś następujące polecenie, aby ustawić użytkownika na www-data?
> 
> ```
> sudo chown -R www-data.www-data /var/www
> ```
> 
>     4. Stripe już tam jest, może skrill w przyszłości.

I se on myaac plugins site, i compiled from github, i try install from site.

**Comment by ModernOTS** [comment]
> 1. O sklepie: wersja jest wąsna? Możesz zobaczyć wwtyczkach/geior-shop-system.json
> 
>     2. Masz admin/pages/gifts.php? Domyślnie jest w wcień wtyczce.
> 
>     3. O logo gildii: prawdopodobnie nie ma prawa do osłusz.
> 
> 
> Czy wykonaj myszki, okutel na www?
> 
> ```
> sudo chown -R www-data.www-data /var/www
> ```
> 
>     4. Stripe tamfi, już iwi, skrill w przyszłości.

i fixed the store but still have problem with guilds, i "sudo chown -R www-data.www-data /var/www" using this before and try adding more like ....images/guild* " i replece  "default" icon from guilds and clear ceche, still thiss same.

**Comment by ModernOTS** [comment]
New problem with buy points, I am tested stripe getaway, money sended and received on stripe account and And I was redirected to my domain with confirmation of a successful transaction.

**Comment by slawkens** [comment]
> New problem with buy points, I am tested stripe getaway, money sended and received on stripe account and And I was redirected to my domain with confirmation of a successful transaction.

Did you refresh site? It sometimes takes few seconds/minutes.

**Comment by slawkens** [comment]
> > 1. O sklepie: wersja jest wąsna? Możesz zobaczyć wwtyczkach/geior-shop-system.json
> >    
> >    2. Masz admin/pages/gifts.php? Domyślnie jest w wcień wtyczce.
> >    3. O logo gildii: prawdopodobnie nie ma prawa do osłusz.
> > 
> > Czy wykonaj myszki, okutel na www?
> > ```
> > sudo chown -R www-data.www-data /var/www
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 4. Stripe tamfi, już iwi, skrill w przyszłości.
> > ```
> 
> i fixed the store but still have problem with guilds, i "sudo chown -R www-data.www-data /var/www" using this before and try adding more like ....images/guild* " i replece "default" icon from guilds and clear ceche, still thiss same.

You may try change file permissions:

chown -R 777 images/guilds

**Comment by ModernOTS** [comment]
> > New problem with buy points, I am tested stripe getaway, money sended and received on stripe account and And I was redirected to my domain with confirmation of a successful transaction.
> 
> Did you refresh site? It sometimes takes few seconds/minutes.

Yeah, I tested 2 payments, all money it's in stripe account but I don't get a points, I have 5.0.2-beta-2 version of store.

**Comment by ModernOTS** [comment]
> > > 1. O sklepie: wersja jest wąsna? Możesz zobaczyć wwtyczkach/geior-shop-system.json
> > >    
> > >    2. Masz admin/pages/gifts.php? Domyślnie jest w wcień wtyczce.
> > >    3. O logo gildii: prawdopodobnie nie ma prawa do osłusz.
> > > 
> > > Czy wykonaj myszki, okutel na www?
> > > ```
> > > sudo chown -R www-data.www-data /var/www
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > 4. Stripe tamfi, już iwi, skrill w przyszłości.
> > > ```
> > 
> > i fixed the store but still have problem with guilds, i "sudo chown -R www-data.www-data /var/www" using this before and try adding more like ....images/guild* " i replece "default" icon from guilds and clear ceche, still thiss same.
> 
> You may try change file permissions:
> 
> chown -R 777 images/guilds


Tested, not working, I am clear cache and cookies.

**Comment by slawkens** [comment]
Sorry I couldn't helped. This is something broken on your setup. Feel free to reopen if you think it's issue in the repo.
