### ISSUE TITLE
Error transferring 'machineIP/login.php - server replied: Internal Server Error

### ISSUE THREAD

**Issue by leonlevir** [slawkens/myaac#251]
### Server configuration
- Operating System:  Ubuntu 22.04
- Web Server (+ version): Apache2
- PHP Version: 8.1.2
- Server name and version (for example: TFS 0.3):  Canary main git clone 13.32
- MyAAC Version: GIT clone

### Client configuration (Your Computer) Virtual Box ubuntu

- Browser: Brave
- Operating System:  Linux

### Description:
I'm trying to install myaac on the canary 13.32 base, znote works perfectly after changing login.php to 13 version, but with myaac I realized that when creating the account the passwords are not being encrypted and when entering ingame I got the following error
![issue1](https://github.com/slawkens/myaac/assets/114972417/9bd0f170-0327-4a6b-b185-d09cb577399b)
![issue2](https://github.com/slawkens/myaac/assets/114972417/0824f07a-b0b4-44e4-a9eb-1c67e782c327)

Is there an error now in 13.32? I don't remember anything that I might have forgotten to configure, and everything else seems to work perfectly.

**Comment by slawkens** [comment]
You can look for an error in /var/log/apache2/error.log, it will show more info why it's failing.
