### ISSUE TITLE
Fatal DB error when creating a character

### ISSUE THREAD

**Issue by Selektiv** [slawkens/myaac#26]
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'rank_id' doesn't have a default value' in /opt/lampp/htdocs/tibia/system/libs/pot/OTS_Base_DB.php:101 Stack trace: #0 /opt/lampp/htdocs/tibia/system/libs/pot/OTS_Base_DB.php(101): PDO->query('INSERT INTO `pl...') #1 /opt/lampp/htdocs/tibia/system/libs/pot/OTS_Player.php(450): OTS_Base_DB->query('INSERT INTO `pl...') #2 /opt/lampp/htdocs/tibia/system/pages/account/create_character.php(155): OTS_Player->save() #3 /opt/lampp/htdocs/tibia/system/pages/accountmanagement.php(128): require('/opt/lampp/htdo...') #4 /opt/lampp/htdocs/tibia/index.php(340): require('/opt/lampp/htdo...') #5 {main} thrown in /opt/lampp/htdocs/tibia/system/libs/pot/OTS_Base_DB.php on line 101
`

**Comment by Selektiv** [comment]
Running Ubuntu 16.x
OTHire 
LAMPP/XAMPP
MySQL

**Comment by slawkens** [comment]
Go to phpmyadmin, select your database and execute this:
`ALTER TABLE players MODIFY `rank_id` int(11) NOT NULL DEFAULT 0  COMMENT 'only if you use __OLD_GUILD_SYSTEM__'`
`ALTER TABLE players MODIFY `guildnick` varchar(255) NOT NULL DEFAULT '' COMMENT 'only if you use __OLD_GUILD_SYSTEM__'`

Also, if you didn't compile with __OLD_GUILD_SYSTEM__, then you can remove those fields in players table: rank_id and guildnick.

**Comment by slawkens** [comment]
This has been fixed. Closing now.
