### ISSUE TITLE
Manage accounts admin page does not work (Solved)

### ISSUE THREAD

**Issue by Scrollog** [slawkens/myaac#262]
### Server configuration
- PHP Version:  8.1 +
- Server name and version (for example: TFS 0.3):  TFS 0.3
- MyAAC Version:  MYAAC_VERSION = '1.0-RC';

### Description:

When accessing the admin page to manage player accounts, the following error occurs:

Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $groups

### Steps To Reproduce:

<YOUR_WEBSITE>/admin/?p=accounts

### Steps to Resolve:

in the admin folder > pages > accounts.php add this line:` $groups = new OTS_Groups_List();`

**Comment by slawkens** [comment]
Hi, thanks! Seems I removed it accidentally in some commit.
