### ISSUE TITLE
Numbers in login only

### ISSUE THREAD

**Issue by K3firo** [slawkens/myaac#269]
- Web Server (+ version):  xampp-7.4.33-0
- Server name and version (for example: TFS 0.3):  tfs 1.2 8.0
- MyAAC Version: myaac-0.8.18

### Description:
How setup to create account can only be numbers in login?
I set client in setup to 800 and still can create acc with NAME in login

**Comment by slawkens** [comment]
You need to have the accounts.number field in accounts table.

If you have accounts.name, then you should delete it, and force your server use accounts.number instead.
