### ISSUE TITLE
Names with spaces

### ISSUE THREAD

**Issue by YohanAugusto** [slawkens/myaac#29]
The website have a problem to load a few contents with spaces.

1 - Edit a character with a space between names;
2 - Edit guilds a space between names.

**Result:**

Not Found
The requested URL /account/character/comment/Player%20Test was not found on this server.

**Comment by slawkens** [comment]
Thanks for reporting this.

I fixed it in latest commit. Download latest version from github (not releases) and see if it works.

Please confirm if it has been fixed. Then I can close this issue.

**Comment by slawkens** [comment]
Sorry I forgot to include twig templates in last commit. I committed them now.

Please try again one more time using latest version.

**Comment by YohanAugusto** [comment]
Editing character info = ok

There is something wrong when setting new nick name

**Result:**

Unknow error occured.

**Comment by YohanAugusto** [comment]
Working! Thanks!
