### ISSUE TITLE
Guilds.php cant invite players

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#3]
Change in line 806 if($rank_of_player->isLoaded()) { to if($rank_of_player->isLoaded()) {

**Comment by slawkens** [comment]
What did you changed? I can't see any change :D

**Comment by MxSoft** [comment]
if($player_rank->isLoaded()) {
 to 
if($rank_of_player->isLoaded()) {

**Comment by slawkens** [comment]
It is already changed.
