### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#32]
Polls duplicate answers 
![polls](https://user-images.githubusercontent.com/6940047/33398764-b51ef12a-d515-11e7-8b10-505f59a38cab.PNG)

**Comment by slawkens** [comment]
What's the point of having same answers as multiple options? :P

This poll script has not been made by me - it has been made by otland member Averatec. So I'm not so up-to-date with it so I won't modify it unless there are any security issues with it.
