### ISSUE TITLE
paypal payment method error

### ISSUE THREAD

**Issue by Mesosot** [slawkens/myaac#33]
after i install the shop and i try to pay throw paypal iget this !

Not Found
The requested URL /?subtopic=paypal was not found on this server.

**Comment by slawkens** [comment]
Read this:
https://otland.net/threads/myaac-plugin-gesior-shop-system.251476/page-2#post-2471008

**Comment by Mesosot** [comment]
\system\pages\points.php
you need to change this line

`<a href="?subtopic/paypal">
`to

`<a href="?subtopic=points&system=paypal">`

**Comment by Mesosot** [comment]
oh okay u replied , why u don't fix in main category
