### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by zcundizmond** [slawkens/myaac#35]
Path to your TFS main directory shows as not found no matter what I do.

Security issues aside (mockup server) - the path is in the root directory at '/root/forgottenserver/'. Am I perhaps formatting this incorrectly?

**Comment by slawkens** [comment]
Is in this directory '/root/forgottenserver/' a config.lua file?

AAC checks if config.lua exist, if not then it displays error message.

**Comment by zcundizmond** [comment]
Yes, this is the directory in which the config.lua file resides.

I was thinking it was maybe a permissions issue, with MyAAC having
difficulty accessing said lua in the root.

**Comment by fao9** [comment]
Hi, when I added my ip to ip.txt, apache return server 500 error. What happend?

**Comment by slawkens** [comment]
Hi. You need to look into your apache2 error.log, there will be message saying what went wrong.

**Comment by slawkens** [comment]
Try this:
```
chown -R apache:apache /var/www
chmod -R 750 /var/www
```

**Comment by slawkens** [comment]
Closing this, as it's not related to MyAAC.

Its a problem with permissions - web server cannot read the MyAAC directory.
