### ISSUE TITLE
Guilds!

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#36]
Hello! In my player i have custom vocations and when for example someone leaves a guild or be named guild leader its vocation change to 0, also in admin when i want to save a change in a player i cant set custom vocation, it says that Vocation id cannot be longer than 1 digits.

**Comment by slawkens** [comment]
Does you players table contains promotion column?

Also, what distribution do you use?

And last question: is this player promoted when leaving guild?

**Comment by MxSoft** [comment]
No, it dosnt have promotion, it works as player_storage
0.4
Yes

**Comment by slawkens** [comment]
Are you sure there's no players.promotion column in your database?

0.4 has such a column.

**Comment by MxSoft** [comment]
Sorry my bad, yes i have

**Comment by slawkens** [comment]
So, I've (hopefully) fixed it in this commit: https://github.com/slawkens/myaac/commit/bcf054104c6dc4391ad18c7d1cb44b7bc856acf6

Let me know if its working for you now.

Its enough when you update OTS_Player.php, rest is optional, or you can update your whole AAC (recommended).

Download to full version here (latest 0.7 to be released soon): https://github.com/slawkens/myaac/archive/0.7.zip

**Comment by MxSoft** [comment]
Fixed i think, i'll post if players report me errors thanx
