### ISSUE TITLE
Forum Quotes not working properly

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#37]
Quotes on big messages doesnt works or idk, i paste you the link to an example:
http://eurotibia.com/?forum/thread/63/0

**Comment by slawkens** [comment]
Thanks. That was caused cause your post included "<<" characters, that was recognized as HTML by MyAAC.

Anyway, I fixed it. Here's fixed version: https://github.com/slawkens/myaac/archive/0.7.zip
Commit that fixes this: https://github.com/slawkens/myaac/commit/5547fd7895086461ac701d3d455ba8862698fbe1

**Comment by MxSoft** [comment]
http://eurotibia.com/?forum/thread/17/0
Error in other type of queted content persist

**Comment by slawkens** [comment]
Did you checked "Enable HTML" in this post? If so, uncheck it.
