### ISSUE TITLE
Victims In characters

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#38]
You added an extra ' in tr bgcolor =
I fixed for you

`
		<br/>
		<table border="0" cellspacing="1" cellpadding="4" width="100%">
			<tr bgcolor="{{ config.vdarkborder }}">
				<td colspan="2" class="white"><b>Victims</b></td>
			</tr>
			{% set i = 0 %}
			{% for frag in frags %}
			<tr bgcolor="{{ getStyle(i) }}">
				<td width="20%" align="center">{{ frag.time|date("j M Y, H:i") }}</td>
				<td>{{ frag.description|raw }}({% if frag.unjustified %}<font size="1" color="red">Unjustified</font>{% else %}<font size="1" color="green">Justified</font>{% endif %})</td>
			</tr>
			{% endfor %}
		</table>
		`

**Comment by slawkens** [comment]
Thanks. Fixed.
