### ISSUE TITLE
Forum log in

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#39]
Idk if this is bug but when im not loged in web and i try to a post in forum the message "You are not logged in. Log in to post on the forum." **appears in a blank page**.
I have my Aac in last rev including your last commit about forums.
Example: http://eurotibia.com/?forum/thread/63

**Comment by slawkens** [comment]
That's caused by your not updated database to the version 21.

You should update common.php and add system/migrations/21.php

It will then automatically update your database to the latest version.
