### ISSUE TITLE
I have a problem installing

### ISSUE THREAD

**Issue by mrtruko** [slawkens/myaac#4]
I have a problem in installing this in linux ubuntu 16.04
Gives me the an 500 error i searched the error con mi log and found this.
Table 'global.myaac_visitors' doesn't exist in...

Here is the full error
`[Thu Jun 29 19:18:44.632098 2017] [:error] [pid 23937] [client 179.151.249.141:39580] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'global.myaac_visitors' doesn't exist in /var/www/html/system/libs/pot/OTS_Base_DB.php:101\nStack trace:\n#0 /var/www/html/system/libs/pot/OTS_Base_DB.php(101): PDO->query('DELETE FROM `my...')\n#1 /var/www/html/system/libs/visitors.php(75): OTS_Base_DB->query('DELETE FROM `my...')\n#2 /var/www/html/system/libs/visitors.php(33): Visitors->cleanVisitors()\n#3 /var/www/html/index.php(90): Visitors->__construct(10)\n#4 {main}\n  thrown in /var/www/html/system/libs/pot/OTS_Base_DB.php on line 101`

**Comment by slawkens** [comment]
Did you installed the AAC successfully?

**Comment by slawkens** [comment]
This should've been fixed now.

Try latest version. You can download it here: https://github.com/slawkens/myaac/archive/master.zip
