### ISSUE TITLE
Unknown column 'myaac_forum.post_html' in 'field list''

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#40]
Error in forum:
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'myaac_forum.post_html' in 'field list'' in /var/www/html/system/libs/pot/OTS_Base_DB.php:101 Stack trace: #0 /var/www/html/system/libs/pot/OTS_Base_DB.php(101): PDO->query('SELECT `players...') #1 /var/www/html/system/pages/forum/show_thread.php(32): OTS_Base_DB->query('SELECT `players...') #2 /var/www/html/system/pages/forum.php(178): require('/var/www/html/s...') #3 /var/www/html/index.php(390): require('/var/www/html/s...') #4 {main} thrown in /var/www/html/system/libs/pot/OTS_Base_DB.php on line 101`

**Comment by slawkens** [comment]
Did you forgot to update common.php or data/migrations/21.php?

There's new database column that will be automatically added into your database when you enter your page.

**Comment by MxSoft** [comment]
Yes i added both files

**Comment by slawkens** [comment]
What do you have in your database in table myaac_config under database_version?

**Comment by MxSoft** [comment]
1 | database_version | 21
-- | -- | --

**Comment by slawkens** [comment]
Yeah, that's cause someone visited your website when you made update and file system/migrations/21.php didn't exist yet.

Change database_version to 20 and refresh the page.

**Comment by MxSoft** [comment]
Now working 100%
