### ISSUE TITLE
online.php

### ISSUE THREAD

**Issue by MxSoft** [slawkens/myaac#42]
![image](https://user-images.githubusercontent.com/6940047/35377179-caaf3f74-0173-11e8-9253-8499845c422a.png)
Error

**Comment by slawkens** [comment]
And what is on line 63 in this file?

Also: what MyAAC version. And what modifications you made to the file, as it seems not to be the original one.

**Comment by MxSoft** [comment]
My custom mods is not the problem i test with oficial version, im using lastest rev
line 63: `                        $context["players"] = ((isset($context["players"]) ? $context["players"] : null) + abs((isset($context["afk"]) ? $context["afk"] : null)));
`

**Comment by MxSoft** [comment]
Problem is gone when i set :	'online_afk' => false,

**Comment by slawkens** [comment]
The problem is in this line of the file: system/templates/online.html.twig:
`{% set players = players + afk|abs %}`

Try changing it to:
`{% set players_count = players_count + afk|abs %}`

And tell me the result! With online_afk enabled of course!

**Comment by MxSoft** [comment]
Fixed, ty so much!
