### ISSUE TITLE
SMTP Mail

### ISSUE THREAD

**Issue by dutchdragon3** [slawkens/myaac#43]
Can someone help me every time i try to verify mail i get a error :S 

[createaccount.php] An error occorred while sending email: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting. Error: 
what do i need to do to fix this ?

here is me PHP : 
	
        // mail
	'mail_enabled' => true, // is aac maker configured to send e-mails?
	'mail_address' => 'test@hotmail.com	', // server e-mail address (from:)
	'mail_admin' => 'test@hotmail.com', // admin email address, where mails from contact form will be sent
	'mail_signature' => array( // signature that will be included at the end of every message sent using _mail function
		'plain' => ''/*'--\nMy Server,\nhttp://www.myserver.com'*/,
		'html' => ''/*'<br/>My Server,\n<a href="http://www.myserver.com">myserver.com</a>'*/
	),
	'smtp_enabled' => true, // send by smtp or mail function (set false if use mail function)
	'smtp_host' => 'smtp.gmail.com', // mail host
	'smtp_port' => 587, // 25 (default) / 465 (ssl, e.g. gmail)
	'smtp_auth' => true, // need authorization?
	'smtp_user' => 'test@gmail.com',
	'smtp_pass' => 'test',

**Comment by slawkens** [comment]
Well, it's more like a support case, you should've posted it on otland Support Boards.

Anyway, your smtp_host seems not to be same as your mail_address host (hotmail vs gmail).

When you want to use hotmail, set smtp_host to 'smtp.live.com', also smtp_user to your actual email and smtp_pass to your password. Also remove spaces in mail_address so it looks like this: 'test@hotmail.com'

**Comment by miqueiaspenha** [comment]
add code in
system/functions.php

```
if($config['smtp_enabled'])
{
    $mailer->IsSMTP();
    $mailer->Host = $config['smtp_host'];
    $mailer->Port = (int)$config['smtp_port'];
    $mailer->SMTPAuth = $config['smtp_auth'];
    $mailer->Username = $config['smtp_user'];
    $mailer->Password = $config['smtp_pass'];
    $mailer->SMTPSecure = $config['smtp_secure']; // Here
}
```
on here
config.local.php

```
$config['smtp_enabled'] = true;
$config['smtp_host'] = 'smtp.gmail.com';
$config['smtp_port'] = 465;
$config['smtp_auth'] = true;
$config['smtp_user'] = 'youmail@gmail.com';
$config['smtp_pass'] = 'yuapass';
$config['smtp_secure'] = 'ssl'; // Here
```

In gmail
Allow less secure apps: ON

**Comment by dutchdragon3** [comment]
i did that now im getting a error Extension missing: openssl

**Comment by miqueiaspenha** [comment]
Are you using GNU Linux? What distribution?

**Comment by dutchdragon3** [comment]
im using windowns but i did enable openssl in the php.ini of me localhost but now i get the same error : [createaccount.php] An error occorred while sending email: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting. Error:

**Comment by miqueiaspenha** [comment]
Do you use two-step authentication in Gmail?

**Comment by dutchdragon3** [comment]
no

**Comment by miqueiaspenha** [comment]
You could do the tutorial with active debug.
http://www.merocode.com/sending-emails-using-phpmailer-via-smtp/

`$mail->SMTPDebug  = 4; `

and show the result here

**Comment by dutchdragon3** [comment]
oke perhaps a stupid question it's because i have 0 knowledge of php 

but i did make a test with this code https://pastebin.com/b6x5rWkK but when i try to acces it it wont work ill get a error 500

**Comment by miqueiaspenha** [comment]
Dear friend, I believe this is not the best solution. I tested the code on the link, on a Windows virtual machine and it worked. Do not use Windows, use GNU Linux (Ubuntu s2 ... ahuahuahauhauhu) to set up your server. ;)

http://www.mediafire.com/file/z42ol3v6j8ic862/mail_gmail.rar

**Comment by slawkens** [comment]
I'm closing it as it seems to be a support matter.

The problem doesn't exist in MyAAC, but is a problem of misconfiguration.
