### ISSUE TITLE
Shop system not working

### ISSUE THREAD

**Issue by stephen92** [slawkens/myaac#45]
Buy Points, Shop Offer, and Shop History do not work.

it says the page does not exist, in the admin panel it does though?

https://www.evolvecraft.com/tibia/

**Comment by slawkens** [comment]
I can't access your site, it seems to have some problems with SSL certificate.

1. Did you installed the plugin in the admin panel? Was the installation successful?

2. Do you have files like points.php and gifts.php in your system/pages directory?

**Comment by stephen92** [comment]
Yeah I am messing with my webhost, not sure if I want to get into OT as I
am no developer. I have the server working etc but its hard to find a good
cheap dev.

I did not know there was a specific shop plugin that needed to be
installed.

No those files are not in the system/pages directory, did I miss a step
somewhere cause the rest of the website works great!

**Comment by slawkens** [comment]
Yes, you need to install an additional plugin to use the shop system.

The plugin file can be downloaded here: https://github.com/slawkens/myaac-gesior-shop-system/releases

Download myaac-gesior-shop-system-v2.0-beta.zip

After installing through admin panel with plugins menu, you should be able to view the shop.

Also, remember to enable gifts_system in your config.php or config.local.php

**Comment by stephen92** [comment]
Perfect thank you so much!

You dont happen to be a developer for lua do you?

**Comment by slawkens** [comment]
I've used to be a Lua developer in the past, working on the TFS 0.3/0.4 engine.

I've created a repository of Lua mods for TFS 0.3/0.4 series - https://github.com/slawkens/tfs-mods

However, actually, I'm mostly occupied working as PHP Developer on MyAAC. But still, I have some basic knowledge of Lua.

**Comment by stephen92** [comment]
Well let me give you some back story

I am 25 years old now, I played Tibia with my younger step brother who
had *Leukemia.
That is what he wanted to spend his time doing.*
So we ended finding Collapser Zulu back in the day, we spent so much time
on there it was ridiculous. Well, as of the 8th of this month, years later
after
Collapser has been shut down, Mike the owner released the full map!

So, I was wanting to release an OT with that map on 10.98 which I have
fully up and running. The only issue is, I am unsure of several things with
OTs, I can easily host it. I have a dedi with OVH,
for my Minecraft servers I have ran for 9 years.

I need someone who can basically get it fully functioning how an OT should
be. Add a few nice scripts for some special features etc. Hopefully get big
lol.


I do not have much spare money for this project but I could do some. I
would more be interested in doing a partnership with a developer, we
essentially would split a percentage based on the income once released.
I would love your thoughts on this and hopefully you may be interested.

**Comment by stephen92** [comment]
hmm, when I go to upload the plugin, it takes it but does not show in the plugin list and the pages still do not work.

in the server files I see it did indeed upload the plugin zip. But it does not seem to be doing anything.

**Comment by slawkens** [comment]
Did you manage to fix this?

I can assist you through TeamViewer if you need.

**Comment by stephen92** [comment]
No I didnt that would be awesome.

**Comment by slawkens** [comment]
Hello,

If you still need help with this, then contact me on skype: **slawkens2** is my username.

**Comment by slawkens** [comment]
Closing, as it seems not an issue with MyAAC.
