### ISSUE TITLE
Delete character bug

### ISSUE THREAD

**Issue by kukas9** [slawkens/myaac#49]
When deleting the character he informs that the deletion was made, the site still continues to point out that the character was not deleted, but in game, it is no longer there, but in the database it is still registered, in the deleting game, but in the bank and site is still active, I do not understand, I restarted everything to see if I had to update or something of the genre, but still the same thing

**Comment by kukas9** [comment]
OTS server Naruto, TFS 0.4, I understand, according to the change he generates in the player table in the deleted column he assumed the value 1, he would like it to disappear from the view on the page, and in case he wants to recover the character he would contact the administration, but in the code he has a warning not to change anything, which I can change to not affect other functions****

**Comment by slawkens** [comment]
If you delete a character, you should see this screen: https://prnt.sc/j0hlu2

It's something that you see?

**Comment by kukas9** [comment]
Yes

**Comment by slawkens** [comment]
So, what is the problem? ;)

Any screenshots?

**Comment by kukas9** [comment]
yes

**Comment by slawkens** [comment]
You use 0.7 or 0.8?

**Comment by kukas9** [comment]
TFS? or MyAAC?

**Comment by slawkens** [comment]
MyAAC. Did you ever hear about TFS 0.7 or 0.8? :D

**Comment by kukas9** [comment]
MyAAC 0.7.10, on TFS only use 0.4 if other higher versions do not know

**Comment by slawkens** [comment]
Edit system/templates/characters.html.twig

Change:
`{% if not player.isHidden() %}`

To:
`{% if not player.isHidden() and not player.isDeleted() %}`

I will add it, but only in MyAAC 0.8-dev.

**Comment by kukas9** [comment]
alright, thx

**Comment by slawkens** [comment]
worked?

**Comment by slawkens** [comment]
Update: Showing deleted characters is now configurable.

Implemented in 0.8-dev (master) branch.
