### ISSUE TITLE
Guilds problem | Possible crash

### ISSUE THREAD

**Issue by YohanAugusto** [slawkens/myaac#51]
It's possible to insert special characters in Guild Name && Guild Rank  && Guild Nick. Some of those character can crash your server if you look at a player. 

Even if you have the latest version of TFS, with fix for the OnLookAt crash, your server can crash. It happens because the line below (player.cpp) can get the "s" value is getting an "<incomplete type>" when looking at a player with special character on this rank / guild.

> s << guildRank->name << " of the " << guild->getName()

**Comment by slawkens** [comment]
Hello. 

Sorry I was on holidays.

Can you post a sample name that can crash the server and should not be allowed? I can't see anything wrong in C++ part you posted. AFAIK double quotes always worked.

**Comment by slawkens** [comment]
I noticed it was only possible to insert special characters in guild nick. In Rank and Guild Name it was not possible. Am I right?

Anyway, It's fixed. Thanks for your report and sorry for late answer.
