### ISSUE TITLE
Not possible to install in a VPS

### ISSUE THREAD

**Issue by Vysius** [slawkens/myaac#52]
Hello, I cant install MyAAC in my VPS. the installation steps says that i must add my IP to the file ip.txt and shows an IP wich is not really my VPS's IP.

How should i bypass this?

**Comment by Vysius** [comment]
Nothing happened here.

**Comment by slawkens** [comment]
It shows IP of the browser/computer you are accessing the website with. You need to add this IP into ip.txt so you will be allowed to complete the installation. This way no one else will be able to do the installation for you.

Or did you already solved your problem, as this issue is closed?
