### ISSUE TITLE
[Suggestion] Account's editor via Admin Panel

### ISSUE THREAD

**Issue by Fluppix** [slawkens/myaac#56]
I've noticed there's a players editor at the admin panel, but nothing to edit a specific account from player (edit their password, email, recovery key, type, etc)

Is this planed?

**Comment by slawkens** [comment]
Hello,

You are right - there is no account editor yet. It is, however, a planned feature.

I currently have no time to do this, so I can't say when it will come.

Any voluntary contributions are highly appreciated.

**Comment by slawkens** [comment]
Hello,

As @Leesneaks stated, he did a great admin panel which includes also Account Editor, which ist by the way now in the master branch! All can try to use it, its awesome!

Closing this now, as it has been implemented already.
