### ISSUE TITLE
Selling Vocations

### ISSUE THREAD

**Issue by kukas9** [slawkens/myaac#57]
I am having difficulty implementing the vocation acquisition by the site, my server is from NTO, instead of using item that the person receives the vocation, or NPC that sells the vocation , I'm trying to do the site, so I'm having problems, in the 1st step is to do this addition of vocations manually using the adminsitrador panel, the 2nd is when I click on buy vocation he create another character with the vocation chosen, 2nd stage more I believe that the 1st depends on the 2nd step, thanks again for the help!
follows the image of the first difficulty I'm having and the code that I believe is right
[https://imgur.com/a/8Gn45P2](url)

In the file "admin-add.html.twig" I added the following code:

`else if(value == 'vocation') {
            $('#extra').append('<input type="number" name="vocation" style="width: 120px;" min="1" placeholder="Vocation" required/>');           
            $('#extra').append('<br/><input type="number" name="looktype" style="width: 120px;" min="1" placeholder="LookType" required/>');
        }`

Gifts.php
inside the "getOfferArray" function, within the "while" i insert:
`$offer_array['vocation'][$i_vocation]['id'] = $data['id'];
            $offer_array['vocation'][$i_vocation]['points'] = $data['points'];
            $offer_array['vocation'][$i_vocation]['description'] = $data['offer_description'];
            $offer_array['vocation'][$i_vocation]['name'] = $data['offer_name'];
            $offer_array['vocation'][$i_vocation]['vocation'] = $data['vocation'];
            $offer_array['vocation'][$i_vocation]['looktype'] = $data['looktype'];
            $i_vocation++;`

inside in "if ($ action == 'admin_add') {", i insert:

`case 'vocation':                                            
                        $vocation = isset($_REQUEST['vocation']) ? $_REQUEST['vocation'] : null;
                        $looktype = isset($_REQUEST['looktype']) ? $_REQUEST['looktype'] : null;
                         if(!$vocation || !is_numeric($vocation)) {
                            $error = 'Please fill all fields. Vocation is empty or its not a number.';
                        }
                        else if(!$looktype || !is_numeric($looktype)) {
                            $error = 'Please fill all fields. LookType is empty or its not a number.';
                        }                       
                       
                        break;`

And in "offer_list" i insert:

`else if($get_offerType == 'vocation' && isset($offer_list['vocation']) && count($offer_list['vocation']) > 0)
        {
            foreach($offer_list['vocation'] as $vocation)
            {
                echo '<tr bgcolor="'.$config['lightborder'].'">
                <td align="center">'.getItemImage($vocation['vocation']).'</td><td><b>'.$vocation['looktype'].'</b><br/>'.'</td><td><b>'.$vocation['name'].'</b><br/>'.$vocation['description'].'</td><td align="center">'.$vocation['points'].'</td><td align="center">';
               
                if(!$logged)
                {
                    echo '<b>Login to buy</b>';
                }
                else
                {
                    echo '<form action="?subtopic=gifts&action=select_player" method=POST><input type="hidden" name="buy_id" value="'.$vocation['vocation'].'"><input type="submit" value="Buy"><br><b>for '.$vocation['points'].' points</b></form>';
                }
                echo '</td></tr>';
            }
`

And to finish, in "confirm_transaction", i insert:

`
elseif($buy_offer['type'] == 'vocation')
                                        {
                                            $query = 'INSERT INTO '.$db->tableName('z_ots_comunication').' (id, name, type, action, param1, param2, param3, param4, param5, param6, param7, delete_it) VALUES (NULL, '.$db->quote($buy_player->getName()).', \'login\', \'give_item\', '.$db->quote($buy_offer['vocation']).', '.$db->quote($buy_offer['item_count']).', 0, 0, \'item\', '.$db->quote($buy_offer['name']).', \'\', \'1\');';
                                            $db->query($query);
                                            $save_transaction = 'INSERT INTO '.$db->tableName('z_shop_history').' (id, comunication_id, to_name, to_account, from_nick, from_account, price, offer_id, trans_state, trans_start, trans_real) VALUES (NULL, '.$db->lastInsertId().', '.$db->quote($buy_player->getName()).', '.$db->quote($buy_player_account->getId()).', '.$db->quote($buy_from).',  '.$db->quote($account_logged->getId()).', '.$db->quote($buy_offer['points']).', '.$db->quote($buy_offer['id']).', \'wait\', '.$db->quote(time()).', \'0\');';
                                            $db->query($save_transaction);
                                            $user_premium_points -= $buy_offer['points'];
                                            add_points($account_logged, -$buy_offer['points']);
                                            echo '<h2>You have bought this item!</h2><b>'.$buy_offer['name'].'</b> added to player <b>'.$buy_player->getName().'</b> for <b>'.$buy_offer['points'].' premium points</b> from your account.<br/>Now patiently wait in game MAX 3 minutes to receive this item!<br />Now you have <b>'.$user_premium_points.' premium points</b>.<br /><a href="?subtopic=gifts">GO TO MAIN SHOP SITE</a>';
                                        }`
Well, I apologize for anything, I'm still learning and I do not know if I'm going right, can give me a light, I thank you again

**Comment by slawkens** [comment]
Hello,

This is the wrong repository to report that bug.

I see your bug report in the myaac-gesior-shop-system repository (https://github.com/slawkens/myaac-gesior-shop-system/issues/3). Could you provide more details there? If you have any more informations of course. I will try to read your report thoroughly tomorrow.
