### ISSUE TITLE
Downloads Module no longer functional

### ISSUE THREAD

**Issue by tornadia** [slawkens/myaac#58]
- Operating System: Ubuntu 16.04
- MyAAC Version: 0.7.10
- PHP Version: 7.0
- Server name and version (for example: TFS 0.3): OTHire 1.0

### Description:
https://github.com/slawkens/myaac/blob/master/system/templates/downloads.html.twig
The links are no longer functional.

### Steps To Reproduce:
Go into download area from any template.

### Solution
Use download URLs from:
https://drive.google.com/drive/folders/0B2-sMQkWYzhGSFhGVlY2WGk5czQ

Also, since there is no longer an officially supported IP Changer, and the most functional from back in the era I am using (7.4-7.72) was Asprate's IP Changer (which to be honest;), the solution could be teaching OT makers how to edit hex addresses depending on the generic Cipsoft client and upload this somewhere so that it could be downloaded by the users, which could in turn be linked in this module. Alternatively, an APP could be written to do the hex edits automatically, which if my memory doesn't deceive me, used to exist back in the day.

e.g.: http://tornadia.hopto.org/?downloads

**Comment by slawkens** [comment]
Hello,

Thanks for your detailed description.

The list you posted seems to be legit, and I am going to change the links.

**Comment by tornadia** [comment]
UPDATE:
Amiroslo created this neat web app: https://myotc.xyz/
Perhaps it could be used as a substitute too. I do think webmasters should be able to provide links to their clients, if they want to use a custom client, instead of the generic URLs as per-provided.

Thanks a lot, @slawkens

**Comment by tobi132** [comment]
Hello,

I have fixed it by moving the downloads page to database. Now the user can edit the page in Admin Panel. By default it uses your link - the clients by Joe.

Here's the commit that fixes it: https://github.com/slawkens/myaac/commit/bc3fd61bde33e45f7bd01f705734e77be653e2b1
