### ISSUE TITLE
Invalid Password+SALT?!+MYAAC

### ISSUE THREAD

**Issue by kukas9** [slawkens/myaac#59]
- Operating System: windows 10
- MyAAC Version: 0.8
- PHP Version: 7.0
- Server name and version (for example: TFS 0.3):  nto vendetta TFS 0.4 narutibia

### Description:
Previous versions of myaac were not having this problem that I remember, what could it be? it is generating salt and my config.lua is configured not to generate, i use rev trunk 3884, work but i receive error "temple is wrong" etc...
but with my distro i receive invalid password, what could it be?

**Comment by kukas9** [comment]
@slawkens I used some versions I had here and it worked, but the current version is even better, could you help me how could I edit it in the code so it does not conflict?
version
[https://imgur.com/XvIBMrD](url)
account work
[https://imgur.com/C77xH3d](url)

**Comment by kukas9** [comment]
@slawkens I used some versions I had here and it worked, but the current version is even better, could you help me how could I edit it in the code so it does not conflict?
version
https://imgur.com/XvIBMrD
account work
https://imgur.com/C77xH3d

**Comment by slawkens** [comment]
Hello,

Currently, I can't think of any change in 0.8 version that could cause it. I will look into more deep tomorrow.

Thanks for your report.

**Comment by slawkens** [comment]
Where can I download your distro to test it? Which option in config.lua can disable salt generating?

Currently, MyAAC detects salt if salt column exists in accounts table. That's the only way it works.

**Comment by kukas9** [comment]
Unfortunately I had to remove everything is redo from scratch so that it works, I have done this for a long time only I remember this detail
