### ISSUE TITLE
cant create guilds on OTHire 0.0.3(1.0)

### ISSUE THREAD

**Issue by angeliker** [slawkens/myaac#60]
when i try to create the guild the aac throw me and error 500 after i checked the error log of my webserver i found this 
`[Wed Oct 31 19:50:55.507999 2018] [core:error] [pid 41411] (13)Permission denied: [client 186.6.190.230:60177] AH00035: access to /images/guilds/default.gif denied (filesystem path '/var/www/html/images/guilds/default.gif') because search permissions are missing on a component of the path, referer: http://tibianas.com/?guilds`

`[Wed Oct 31 19:51:03.108948 2018] [php7:error] [pid 41430] [client 186.6.190.230:60181] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'motd' doesn't have a default value in /var/www/html/system/libs/pot/OTS_Base_DB.php:101\nStack trace:\n#0 /var/www/html/system/libs/pot/OTS_Base_DB.php(101): PDO->query('INSERT INTO `gu...')\n#1 /var/www/html/system/libs/pot/OTS_Guild.php(199): OTS_Base_DB->query('INSERT INTO `gu...')\n#2 /var/www/html/system/pages/guilds/create.php(108): OTS_Guild->save()\n#3 /var/www/html/system/pages/guilds.php(30): require('/var/www/html/s...')\n#4 /var/www/html/index.php(386): require('/var/www/html/s...')\n#5 {main}\n  thrown in /var/www/html/system/libs/pot/OTS_Base_DB.php on line 101, referer: http://tibianas.com/?subtopic=guilds&action=create`

**Comment by slawkens** [comment]
Hello,

Thanks for your report.

I fixed the error. Please download corresponding file either from 0.7 branch or master and follow the installation again.

Let me know if the error persists.
