### ISSUE TITLE
Problem when install

### ISSUE THREAD

**Issue by dzikibocian** [slawkens/myaac#72]
### Server configuration
- Operating System:  Ubuntu 16.04
- Web Server (+ version):  nginx
- PHP Version:  7.0
- Server name and version (for example: TFS 0.3):  otxserver 3 (base tfs 1.3)
- MyAAC Version:  0.7.1.0

I have a problem. When I try to install in step no. 6, this error pops up for me:

```
The config file can not be found. Is your path to the correct server directory? Return and check again.
Notice: Undefined index: var_server_path in /home/otsmanager/www/public_html/install/includes/config.php on line 9
```

The server path is good and I have no idea how to fix it.

**Comment by Leesneaks** [comment]
i got a similar error when the path was incorrect.
What are you entering?

**Comment by tornadia** [comment]
Please delete this; the OP didn't specify how to replicae this bug and it seems pretty self explaining.
