### ISSUE TITLE
myaac_monsters table column loot problem

### ISSUE THREAD

**Issue by Jarofir** [slawkens/myaac#79]
Hello,
I've spoted an issue that for some monsters in page "creatures.php" you can not see loot. This is due to column loot lenght. Some of the loot is cut in the middle, then $loot variable is not correct - in example try Demon or Dragon.
If you extend loot column everything works fine.

Try use `ALTER TABLE myaac_monsters MODIFY loot VARCHAR(65353);`

**Comment by ivenspontes** [comment]
best create another table myaac_monsters_loots

```sql
CREATE TABLE `myaac_monsters_loots` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`monster_id` int(11) NOT NULL,
	`loot` varchar(50) NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`monster_id`) REFERENCES myaac_monsters (`id`)
);
```
and take item by item.

**Comment by Jarofir** [comment]
@ivenspontes It would be slower. In JSON version you get whole data by one request. So your DB is not used as much as it would be if every User would use SELECT. If you have 1000 monsters, and every monster has 10 items in loot, there is 10 000 records to check. It's not efficient.

**Comment by ivenspontes** [comment]
Then, can use type TEXT.

**Comment by Jarofir** [comment]
I've extended loot collumn to VARCHAR(65353) and it works fine.

**Comment by slawkens** [comment]
65353 might be a bit extreme, but I will increase that field for sure.

Thanks for the info.

**Comment by Jarofir** [comment]
In SQLServer you have varchar(max), but there is no such thing in MySQL so i suggested max lenght (or about max length).
