### ISSUE TITLE
bug guild view rank

### ISSUE THREAD

**Issue by matheusjp2** [slawkens/myaac#81]
![Screenshot_25](https://user-images.githubusercontent.com/32050328/57562193-ece80d80-7366-11e9-9046-0bda771a8985.png)
bug guild view rank

**Comment by slawkens** [comment]
What template is that?

And more description of the bug, please. Like version of the MyAAC, and what do you mean with that screenshot.

**Comment by slawkens** [comment]
I am closing this cause no enough info. Please be more descriptive and then open the ticket again if you wish.
