### ISSUE TITLE
add function getItems pleas.

### ISSUE THREAD

**Issue by matheusjp2** [slawkens/myaac#83]
Hello
Pleas add function getItems gesior for myaac ;/
![Screenshot_9](https://user-images.githubusercontent.com/32050328/58365729-cb2a7280-7e9e-11e9-8edc-3df054541d9e.png)

**Comment by tobi132** [comment]
Hello,

It won't be compatible with Gesior anyways because we use different class names.

So I will close it. You may reopen if you still wish it.
