### ISSUE TITLE
Problem with Rewrite MOD, Error 404 Page Not Found

### ISSUE THREAD

**Issue by d0gw4r** [slawkens/myaac#84]
Hi, I turned rewrite ON, in **.htacess**, but now I'm getting this error when I try to go through other pages. Only my home page is working fine.

> 404 Not Found
> nginx/1.4.6 (Ubuntu)

I renamed .htacess.dist to .htacess and put the value 'true' in config.php.

Thanks.

**Comment by slawkens** [comment]
Hello,

.htaccess files are read only by apache web server. But you are using nginx, its different web server.

For nginx, check this sample file, and configure your web server accordingly:
(its in /etc/nginx/nginx.conf)
https://github.com/slawkens/myaac/blob/master/nginx-sample.conf

**Comment by d0gw4r** [comment]
When I put this code in the nginx.conf, it won't restart, says fail.

**Comment by slawkens** [comment]
Sorry not in nginx.conf, but in sites-enabled/ folder.

**Comment by d0gw4r** [comment]
It says "fascgi_pass is not allowed here", i don't know why this is happening.

**Comment by slawkens** [comment]
Can I assist you through TeamViewer? Please send me a discord message:  slawkens#7932

**Comment by slawkens** [comment]
Closing as its not a MyAAC related issue, but the problem with configuration.
