### ISSUE TITLE
code broken, possibly sql injection

### ISSUE THREAD

**Issue by lordtyrion321** [slawkens/myaac#85]
Theres a problem in the codes that people can use probably sql injection and become GM or change your informations.

**Comment by gpedro** [comment]
Can you specify which feature is vulnerable to sql injection?

**Comment by mrhultin** [comment]
No he can't, I think he might have been unaware that PDO's bind takes care of this issue itself.

**Comment by tobi132** [comment]
it's hard to verify as the queries are escaped everywhere, so I don't have reason to believe you until you post some confirmation :wink:

Until then, I close this one. Feel free to re-open if you find something vulnerable.
