### ISSUE TITLE
Error on new installation

### ISSUE THREAD

**Issue by EPuncker** [slawkens/myaac#87]
### Server configuration
- Operating System: Windows 10
- Web Server (+ version): UwAmp 3.1.0
- PHP Version: 7.0.3
- Server name and version: OTX based on TFS 1.3
- MyAAC Version: latest one not from release

### Client configuration (Your Computer)

- Browser: Chrome
- Operating System: Windows 10

### Description:
Error when finishing installation:

![2019-07-16 23_57_10-Window](https://user-images.githubusercontent.com/4684880/61343879-bd052c80-a825-11e9-8d3c-8c6c67874771.jpg)

### Steps To Reproduce:

1. [used this database](https://raw.githubusercontent.com/opentibiabr/OTServBR-Global/develop/schema.sql), no edits
2. downloaded latest my-aac
3. did the usual install and boom, the error

**Comment by tobi132** [comment]
Thanks for the report. This has been just fixed.

**Comment by EPuncker** [comment]
thanks
