### ISSUE TITLE
BUG on Your Template

### ISSUE THREAD

**Issue by Sargitarium** [slawkens/myaac#90]
I'm SEE your bealtiful templates, and on PAXTON1 templete have a bug http://demo.my-aac.org/experienceTable see that to view BUG....

**Comment by tobi132** [comment]
what's the bug? I can't see anything wrong there.

**Comment by gpedro** [comment]
is just table overflowing the content.

<img width="734" alt="Captura de Tela 2019-08-17 às 19 07 46" src="https://user-images.githubusercontent.com/2898638/63218146-62136d80-c122-11e9-9c61-9c8f39b0449e.png">
<img width="762" alt="Captura de Tela 2019-08-17 às 19 07 54" src="https://user-images.githubusercontent.com/2898638/63218147-62ac0400-c122-11e9-94cf-0f8fd5aa9be1.png">

**Comment by tobi132** [comment]
Thanks @gpedro.

It has been fixed by adjusting experiencetable_columns and experiencetable_rows in config.php
