### ISSUE TITLE
Database Encryption

### ISSUE THREAD

**Issue by RajasEdge** [slawkens/myaac#92]
#11 # Server configuration
- Operating System: Windows 10
- Web Server (+ version):  XAMPP Version 7.3.9
- PHP Version:  PHP 7.3.9
- Server name and version (for example: TFS 0.3): TFS 1.3 https://github.com/opentibiabr/OTServBR-Global 12.00

- MyAAC Version:  0.7.7

### Steps To Reproduce:

Error in function database_encryption for sha1, sha256.

**Comment by slawkens** [comment]
What exactly is the problem you are having? What doesn't work?

TFS 1.3 uses sha1, which MyAAC uses too.
