### ISSUE TITLE
Imagens Missing

### ISSUE THREAD

**Issue by augustorajas** [slawkens/myaac#93]
?subtopic=guilds&action=manager&guild=(GuildName)

![delete](https://user-images.githubusercontent.com/26828284/68103295-e8835400-feb4-11e9-8e37-9afc607b6e16.png)
 
This image is missing from the directory: templates/tibiacom/images/news/delete.png

**Comment by RajasEdge** [comment]
I would like to help more if you could give me your email or skype would be better.

**Comment by tobi132** [comment]
Hello,

Thanks for your report.

I have fixed that one by adding the image into images/news directory.
