### ISSUE TITLE
Guild dont have INVITE button

### ISSUE THREAD

**Issue by Sargitarium** [slawkens/myaac#95]
When create guild don't apear button to invite member with tibia template...

**Comment by Sargitarium** [comment]
![image](https://user-images.githubusercontent.com/42014600/68447045-4f5a8300-01bd-11ea-9e50-d3aeb1bae9f2.png)

**Comment by Sargitarium** [comment]
All times cleanup players and cleanup guilds command... but player dont member of your own guild

![image](https://user-images.githubusercontent.com/42014600/68448135-479cdd80-01c1-11ea-8696-2aaa0fe1a255.png)

**Comment by Sargitarium** [comment]
Hey Slawkens can you help here man....

**Comment by tobi132** [comment]
What distro you use?

**Comment by Sargitarium** [comment]
I use TFS 1.2 OTBR....

Logged yes.... Charpman too....

But i'm alread fix the bug..... thx for not support...
