### ISSUE TITLE
Last Kills page error

### ISSUE THREAD

**Issue by Sargitarium** [slawkens/myaac#98]
SERVER OTBR TFS 1,2
Using MYAAC 0.7.11

LAST KILLS PAGE show list os deaths without organization..... See that image.... and other detail kill count don't work

![image](https://user-images.githubusercontent.com/42014600/71141388-b9217000-21f2-11ea-8b52-c2cb9ff57961.png)

I want as possible... to show last kills/death with organized page.... See image

![image](https://user-images.githubusercontent.com/42014600/71141488-0a316400-21f3-11ea-9f52-6ed8ad4c7fdd.png)

This is a best visual to see....

Thx for helping

**Comment by tobi132** [comment]
Hello,

Thanks for your report.

I fixed it in this commit: https://github.com/slawkens/myaac/commit/be9ce34dc8fa0108395fac4bb1e425480eb2ce23

Just re-download system/pages/lastkills.php and system/templates/lastkills.html.twig

BTW. Seems that you're using 0.8-dev, not 0.7.11
