### ISSUE TITLE
Last Kills Bug

### ISSUE THREAD

**Issue by MoisesFV** [slawkens/myaac#99]
all with the same time and data

![1](https://user-images.githubusercontent.com/27247705/71548163-08049d80-2989-11ea-8b1a-1a615111908e.png)

**Comment by tobi132** [comment]
what version of otserv?

**Comment by MoisesFV** [comment]
OTXServer 8.6

**Comment by tobi132** [comment]
in file system/pages/lastkills.php

try changing:
~~'date' => $death['date'],~~ 

to:
~~'time' => $death['date'],~~ 

and tell me if it worked

**Comment by MoisesFV** [comment]
It worked. I love you
